= Custom predicate support
:page-aliases: boost_test/testing_tools/custom_predicates.adoc

Even though supplied testing tools cover wide range of possible checks and provide detailed report on cause of error in
some cases you may want to implement and use custom predicate that perform complex check and produce intelligent report
on failure. To satisfy this need testing tools implement custom predicate support. There two layers of custom predicate
support implemented by testing tools toolbox: with and without custom error message generation.

The first layer is supported by {boost_level_predicate} family of testing tools. You can use it to check any custom
predicate that reports the result as boolean value. The values of the predicate arguments are reported by the tool
automatically in case of failure.

// tag reference: doc/modules/ROOT/examples/example30.run-fail.cpp
:bt-name: example30
:bt-rule: run-fail
:bt-descr: Custom predicate support using {boost_level_predicate}
include::partial$bt_example.adoc[]

To use second layer your predicate has to return {class_predicate_result}.

This class encapsulates boolean result value along with any error or information message you opt to report.

Usually you construct the instance of class {class_predicate_result} inside your predicate function and return it by
value. The constructor expects one argument - the boolean result value. The constructor is implicit, so you can simply
return boolean value from your predicate and {class_predicate_result} is constructed automatically to hold your value
and empty message. You can also assign boolean value to the constructed instance. You can check the current predicate
value by using `operator!` or directly accessing public read-only property `p_predicate_value`. The error message is
stored in public read-write property `p_message`.

// tag reference: doc/modules/ROOT/examples/example31.run-fail.cpp
:bt-name: example31
:bt-rule: run-fail
:bt-descr: Custom predicate support using class {class_predicate_result}
include::partial$bt_example.adoc[]
