= Writing unit tests
:page-aliases: boost_test/testing_tools.adoc

Once a test case has been declared, the body of this test should be written. A test case is a
sequence of operations in which *assertions* are inserted. Those assertions evaluate _statements_ that implement the expectation being validated,
and report failures and/or information in a uniform manner, depending on the xref:utf_reference/rt_param_reference.adoc#log_level[log level].

The {utf}'s supplies a toolbox of assertions to ease the creation and maintenance of test cases and
provide a uniform error reporting mechanism. The toolbox supplied is in most part in a form of macro declarations.
An (almost) unique interface to all of them implemented by the macro {boost_test}.

NOTE: All macros arguments are calculated once, so it's safe to pass complex expressions in their place.

All tools automatically supply an error location: a file name and a line number, which can also be overridden.

[CAUTION]
====
The testing tools are intended for unit test code rather than library or production code, where throwing exceptions, using `assert()`,
`boost::concept_check` or `BOOST_STATIC_ASSERT()` may be more suitable ways to detect and report errors.
====

For a list of all supplied testing tools and usage examples, see the xref:testing_tools/summary.adoc[summary]
or the xref:utf_reference/testing_tool_ref.adoc[reference].

[#extended_comparison]
== Extended comparisons support
