= Time-out for test cases
:page-aliases: boost_test/testing_tools/timeout.adoc

The _Unit Test Framework_ provides the decorator xref:{decorator_timeout}[`timeout`] that specifies a time-out for a specific *test unit*.
The argument time is always expressed in *seconds ans wall-clock* time.

For test-cases, the time-out value sets the maximum allowed duration for the test. If this time is
exceeded, the test case is reported as failed. On some systems, the _Unit Test Framework_ is able to force the test-case
to stop through a `SIGALRM` signal (see below).

For test-suites, the time-out value sets the maximum allowed duration for the entire suite to complete. This duration
is the accumulated time of all the test-cases contained in the sub-tree rooted on the test-suite, plus some extra
execution time needed by the _Unit Test Framework_. For each test-units under a test-suite with time-out, the maximum allowed duration
is set as being the test-suite time out minus the accumulated execution time before the execution of the test-unit.
If this test-unit is a test-case, it is equivalent to setting the decorator xref:{decorator_timeout}[`timeout`] to the test-case
with a time-out value expressed as before.

In case the test-suite times out, the
suite is flagged as `timed-out` and `failed`, and all the test units (suites and cases) that have not been executed
up to the time-out point are all skipped.

// tag reference: doc/modules/ROOT/examples/decorator_11.run-fail.cpp
:bt-name: decorator_11
:bt-rule: run-fail
:bt-descr: decorator timeout
include::partial$bt_example.adoc[]

[NOTE]
====
The macro
  `BOOST_SIGACTION_BASED_SIGNAL_HANDLING` is defined
  if Boost.Test is able to force the test-case to stop. This feature is for instance not supported on Windows.
  The _Unit Test Framework_ will still be able to report the test-case as failed (once the test-case finishes).
====

NOTE: The support of test suite level time-out has been added in xref:change_log.adoc#ref_CHANGE_LOG_3_10[Boost 1.70 / _Unit Test Framework_ v3.10]
