= Contexts
:page-aliases: boost_test/test_output/test_tools_support_for_logging/contexts.adoc

Contexts are a facility provided by the _Unit Test Framework_ in order to be able to trace the location of assertions better. To grasp
the idea, consider the following example:

[source,cpp]
----
void test_operations(Processor& processor, int limit)
{
  for (int i = 0; i < limit; ++i) {
    BOOST_TEST(processor.op1(i));
    for (int j = 0; j < i; ++j) {
      BOOST_TEST(processor.op2(i, j));
    }
  }
}
----

In case of failure, in order to see in the logs at which point of the loops the failure occurred, we need some extra
information in the assertion, which can be achieved for instance xref:testing_tools/reports.adoc#custom_messages[the following way]:

[source,cpp]
----
BOOST_TEST(processor.op1(i));
----

replaced by

[source,cpp]
----
BOOST_TEST(processor.op1(i), "With parameter i = " << i);
----

We see in this trivial example that a context, which is the variable `i` in this case, should be acknowledged by the
assertion `BOOST_CHECK` in a particular way. In the approach above, this is done by adding a message to the assertion
itself.

What if the context is more complex than that? In case the complexity of the context increases, the fact that the
assertion and the context is tightly coupled as in the approach above is difficult to maintain:

[source,cpp]
----
void test_operations(Processor& processor, int limit, int level)
{
  for (int i = 0; i < limit; ++i) {
    BOOST_TEST(processor.op1(i),
               "With optimization level " << level << ", With parameter i = " << i);
    for (int j = 0; j < i; ++j) {
      BOOST_TEST(processor.op2(i, j),
                 "With optimization level " << level <<
                 ", With parameter i = " << i << ", With parameter j = " << j);
    }
  }
}

BOOST_AUTO_TEST_CASE(test1)
{
  Processor processor;

  for (int level = 0; level < 3; ++level) {
    processor.optimization_level(level);
    test_operations(processor, 2, level);
  }
}
----

Note the length of the messages, the repetition, and the fact, that we pass argument `level` to function
`test_operations` only for the sake of generating an error message in case of a failure.

Therefore, *loose* coupling between the context of an assertion and the assertion point is a property that is desirable.

[#ref_BOOST_TEST_INFO]
== Assertion-bound context

`BOOST_TEST_INFO` can be used to define an error message to be bound to the first following assertion. If (and only
if) the assertion fails, the bound message will be displayed along:

// tag reference: doc/modules/ROOT/examples/example80_contexts.run-fail.cpp
:bt-name: example80_contexts
:bt-rule: run-fail
:bt-descr: Assertion-bound context
include::partial$bt_example.adoc[]

The information composed inside `BOOST_TEST_INFO` is bound only to the first assertion
following the declaration. This information is only displayed if the assertion fails; otherwise the message is
discarded. The `BOOST_TEST_INFO` declaration does not have to immediately precede the assertion, it is allowed to
intertwine them with other instructions, they can even be declared in different scopes. It is also possible to
bind more than one information to a given assertion.

With `BOOST_TEST_INFO`, we can improve our initial example as follows:

[source,cpp]
----
void test_operations(Processor& processor, int limit, int level)
{
  for (int i = 0; i < limit; ++i) {
    BOOST_TEST_INFO("With optimization level " << level);
    BOOST_TEST_INFO("With parameter i = " << i);
    BOOST_TEST(processor.op1(i));
    for (int j = 0; j < i; ++j) {
      BOOST_TEST_INFO("With optimization level " << level);
      BOOST_TEST_INFO("With parameter i = " << i);
      BOOST_TEST_INFO("With parameter j = " << j);
      BOOST_TEST(processor.op2(i, j));
    }
  }
}

BOOST_AUTO_TEST_CASE(test1)
{
  Processor processor;

  for (int level = 0; level < 3; ++level) {
    processor.optimization_level(level);
    test_operations(processor, 2, level);
  }
}
----

[#ref_BOOST_TEST_CONTEXT]
== Scope-bound context

In the previous example, the information stored inside the calls to `BOOST_TEST_INFO` were all consumed by the next assertion. There are cases
where we would like this information be persistent for the current scope. _Unit Test Framework_ provides two tools to achieve this:

* `BOOST_TEST_CONTEXT` defines a diagnostic message and a scope. The message is bound to every assertion in that scope,
and is displayed along with every failed assertion.
* `BOOST_TEST_INFO_SCOPE` acts the same as `BOOST_TEST_INFO`, but the stored context information is bound to all the assertions
that follow the call to `BOOST_TEST_INFO_SCOPE` within the current scope.

TIP: Since Boost xref:change_log.adoc#ref_CHANGE_LOG_3_10[Boost 1.70], `BOOST_TEST_CONTEXT` can accept multiple arguments.

TIP: `BOOST_TEST_INFO_SCOPE` has been introduced in xref:change_log.adoc#ref_CHANGE_LOG_3_10[Boost 1.70].

// tag reference: doc/modules/ROOT/examples/example81_contexts.run-fail.cpp
:bt-name: example81_contexts
:bt-rule: run-fail
:bt-descr: Scope-bound context
include::partial$bt_example.adoc[]

In the previous example, there is an opening brace right after `BOOST_TEST_CONTEXT`: this pair of braces defines the scope in which
the diagnostic message is in effect. If there is no braces, the scope applies only to the following statement.
`BOOST_TEST_CONTEXT` declarations can nest.

With `BOOST_TEST_CONTEXT`, we can further improve our initial example, by putting variable `level` into a scope-level context
and not pass it as function parameter:

[source,cpp]
----
void test_operations(Processor& processor, int limit)
{
  for (int i = 0; i < limit; ++i) {
    BOOST_TEST_INFO("With parameter i = " << i);
    BOOST_TEST(processor.op1(i));
    for (int j = 0; j < i; ++j) {
      BOOST_TEST_INFO("With parameter i = " << i);
      BOOST_TEST_INFO("With parameter j = " << j);
      BOOST_TEST(processor.op2(i, j));
    }
  }
}

BOOST_AUTO_TEST_CASE(test1)
{
  Processor processor;

  for (int level = 0; level < 3; ++level) {
    BOOST_TEST_CONTEXT("With optimization level " << level) {
      processor.optimization_level(level);
      test_operations(processor, 2);
    }
  }
}
----

If we observe that variable `i` also applies in a certain scope, we can improve our example further still.

// tag reference: doc/modules/ROOT/examples/example82_contexts.run-fail.cpp
:bt-name: example82_contexts
:bt-rule: run-fail
:bt-descr: Using contexts
include::partial$bt_example.adoc[]

Finally, it is possible to pass several arguments to `BOOST_TEST_CONTEXT`, which is more convenient than having
several scopes:

// tag reference: doc/modules/ROOT/examples/example83_contexts.run-fail.cpp
:bt-name: example83_contexts
:bt-rule: run-fail
:bt-descr: Multiple arguments to `BOOST_TEST_CONTEXT`
include::partial$bt_example.adoc[]

`BOOST_TEST_INFO_SCOPE` is convenient when you augment the current scope information as new information arrives.
The following example calls several time a quadratic polynomial estimation function with random polynomial. As the
random values are drawn in a loop, they are placed in the current scope with `BOOST_TEST_INFO_SCOPE`, which allows us
to easily debug the function.

// tag reference: doc/modules/ROOT/examples/example84_contexts.run-fail.cpp
:bt-name: example84_contexts
:bt-rule: run-fail
:bt-descr: Sticky context with `BOOST_TEST_INFO_SCOPE`
include::partial$bt_example.adoc[]
