= Controlling outputs
:page-aliases: boost_test/test_output.adoc

The output produced by a test module is one of the major assets the _Unit Test Framework_ brings to users. In comparison with any
kind of manual/assert based solution the _Unit Test Framework_ provide following services:

[cols="1,3"]
|===
|All test errors are reported uniformly
a|
The test execution monitor along with standardized output from all included
  xref:testing_tools/index.adoc[testing tools] provides uniform reporting for all errors
  including fatal errors, like memory assess violation and uncaught exceptions.

|Detailed information on the source of an error
a|
The _Unit Test Framework_ test tool's based assertion provides as much information as possible about cause of error,
  usually allowing you to deduce what is wrong without entering the debugger or core analysis.

|Separation of the test errors description (test log) from the results report summary (test results report)
a|
The information produced during test execution, including all error, warning and info messages from the test
  tools, executed test units notification constitute the *test log*.

Once testing is completed the _Unit Test Framework_ may produce a summary *test report* with
  different levels of detail.

|Flexibility in what is shown in the output
a|
The _Unit Test Framework_ provides the ability to configure what is shown in both the test log and the test report. The
  configuration is supported both at runtime (from the command line) and at compile time from within a
  test module.

|Flexibility in how output is formatted
a|
The _Unit Test Framework_ provides the ability to configure the format of the test module output. At the moment only
  xref:test_output/log_formats.adoc[three formats]
  are supported by the _Unit Test Framework_ itself. However the well defined public interface allows you to
  xref:test_output/logging_api.adoc#custom_log_formatter[customize] an output for
  your purposes.

|===
