= Tools supports for logging
:page-aliases: boost_test/test_output/test_tools_support_for_logging.adoc

[#testing_tool_output_disable]
== Logging user defined types

Most of the xref:testing_tools/index.adoc[testing tools] print values of their
arguments to the output stream in some form of log statement. If arguments type does not support

[source,cpp]
----
operator<<(std::ostream&, ArgumentType const&);
----

interface, you will get a compilation error.

The _Unit Test Framework_ supports three different methods for logging user defined types:

. through the `operator<<` for that specific type: any type that implements the above interface has direct support for
logging,
. through a customization point responsible for logging a specific type, which is less intrusive than the implementation
of `operator<<`. This is explained in more details in xref:test_output/test_tools_support_for_logging.adoc#ref_log_output_custom_customization_point[this section],
. by prohibiting the xref:testing_tools/index.adoc[testing tools] from logging argument values for
specified type through xref:{boost_test_dont_print_log_value}[`BOOST_TEST_DONT_PRINT_LOG_VALUE`].
This is explained in more details in xref:test_output/test_tools_support_for_logging.adoc#ref_log_output_custom_avoid_printing[this section].

[#ref_log_output_custom_customization_point]
=== User type customization point for logging

It is possible to indicate a function, `boost_test_print_type`, to _Unit Test Framework_ that is responsible for the printing of a user defined type, without
the need to override the `operator<<` for that specific type. This is convenient for instance when
the `operator<<` has already been defined for other needs.

The syntax follows the `operator<<`, and this function should be in the same namespace as the type:

[source,cpp]
----
std::ostream& boost_test_print_type(std::ostream& ostr, ArgumentType const& right);
----

// tag reference: doc/modules/ROOT/examples/logger-customization-point.run-fail.cpp
:bt-name: logger-customization-point
:bt-rule: run-fail
:bt-descr: Logging customization point usage
include::partial$bt_example.adoc[]

[#ref_log_output_custom_avoid_printing]
=== Prohibiting the printing of a specific type

To prohibit the printing of a specific type, use the following statement on file level before first
test case that includes statement failing to compile:

[source,cpp]
----
BOOST_TEST_DONT_PRINT_LOG_VALUE(ArgumentType)
----

// tag reference: doc/modules/ROOT/examples/example32.run-fail.cpp
:bt-name: example32
:bt-rule: run-fail
:bt-descr: BOOST_TEST_DONT_PRINT_LOG_VALUE usage
include::partial$bt_example.adoc[]

[#test_output_macro_message]
== Custom messages

The macro xref:{boost_test_message}[`BOOST_TEST_MESSAGE`] is intended to be used for the purpose of injecting an additional message into the
_Unit Test Framework_ test log. These messages are not intended to indicate any error or warning conditions, but rather as
information/status notifications. The macro signature is as follows:

xref:{boost_test_message}[`BOOST_TEST_MESSAGE`](test_message);

The test_message argument can be as simple as C string literal or any custom expression that you can produce with in a
manner similar to standard `std::iostream` operation.

[IMPORTANT]
====
Messages generated by this tool do not appear in test log output with default value of the active log level
   threshold. For these messages to appear the active log level threshold has to be set to a value below or equal
   to "message".
====

// tag reference: doc/modules/ROOT/examples/example21.run.cpp
:bt-name: example21
:bt-rule: run
:bt-descr: xref:{boost_test_message}[`BOOST_TEST_MESSAGE`] usage
include::partial$bt_example.adoc[]
