= Test unit filtering
:page-aliases: boost_test/runtime_config/test_unit_filtering.adoc

The {utf} offers a number of ways to run only a subset of all test cases registered in the test tree.

[#ref_default_run_status]
== Default run status

Each test unit (either test case or test suite) has an associated _default run status_. It can assume one of the three values:

. _true_ -- this means that, unless some runtime parameters specify otherwise, the test unit is designated to be run.
. _false_ -- this means that, unless some runtime parameters specify otherwise, the test unit is designated _not_ to be run.
. _inherit_ -- this means that the test unit's default run status is the same as that of its immediate parent test unit. This is applied recursively.

Initially, the master test suite has default run status set to _true_. All other test units have default run status set to _inherit_.
This implies that, unless any additional configuration is applied, all tests are designated to be run.

You can set a different default run status in any test unit by using xref:tests_organization/decorators.adoc[decorators]:
{decorator_disabled}, {decorator_enabled} and {decorator_enable_if}. The default run status is set once, upon testing program
initialization, and cannot be changed. The disabled tests are not executed by default, but are still present in the test tree,
and are listed along with other tests when you use command-line argument
xref:utf_reference/rt_param_reference.adoc#list_content[`list_content`].

// tag reference: doc/modules/ROOT/examples/decorator_20.run-fail.cpp
:bt-name: decorator_20
:bt-rule: run-fail
:bt-descr: default run status
include::partial$bt_example.adoc[]

[#ref_dynamic_test_dependency]
== Dynamic test dependencies

Additionally, it is possible to statically associate a test unit with a condition. This associated condition is evaluated immediately
before executing the test unit. If the condition is met, the test unit is executed. Otherwise, the test unit is _skipped_.
It is possible to add two dependencies:

. Upon another test unit. In this case the decorated test case is skipped if the test unit specified in the dependency is either
failed or skipped or disabled. This can be declared with decorator {decorator_depends_on}.
. Upon an arbitrary predicate. This can be declared with decorator {decorator_precondition}.

[#ref_command_line_control]
== Command-line control

Static configuration of the test-case filtering is used by default, unless command-line filtering is applied. With command-line argument
{param_run_test} it is possible to alter the static pre-set in a number of ways:

. Ignore the static configuration and manually specify test cases to be run.
. Augment the statically defined set by enabling the disabled test cases.
. Shrink the statically defined set by disabling some of the enabled test cases.

[#ref_command_line_control_absolute]
=== Absolute specification

Term 'absolute' in this context means that the default run status of the test units, which has been statically set up,
is completely ignored and the tests to be run are specified manually from scratch. First, in order to learn what test
units are registered in the test tree the user needs to use command-line argument
xref:utf_reference/rt_param_reference.adoc#list_content[`list_content`].
Next, in order to specify a set of test cases, the user needs to use command-line argument
{param_run_test} with absolute value:

[source,cpp]
----
> test_program --run_test=<test_set>
----

The format of `<test_set>` value can assume a number of forms. Given the following program:

[source,cpp]
----
#define BOOST_TEST_MODULE example
#include <boost/test/included/unit_test.hpp>

using boost::unit_test::label;

BOOST_AUTO_TEST_CASE(test_1, *label("L1")) {}
BOOST_AUTO_TEST_CASE(test_2, *label("L1")) {}

BOOST_AUTO_TEST_SUITE(suite_1)

  BOOST_AUTO_TEST_SUITE(suite_1)
    BOOST_AUTO_TEST_CASE(test_1) {}
    BOOST_AUTO_TEST_CASE(test_2) {}
  BOOST_AUTO_TEST_SUITE_END()

  BOOST_AUTO_TEST_SUITE(suite_2)
    BOOST_AUTO_TEST_CASE(test_1, *label("L2")) {}
    BOOST_AUTO_TEST_CASE(test_2, *label("L2")) {}
  BOOST_AUTO_TEST_SUITE_END()

  BOOST_AUTO_TEST_CASE(test_1, *label("L1")) {}
  BOOST_AUTO_TEST_CASE(test_2) {}
  BOOST_AUTO_TEST_CASE(test_2A) {}

BOOST_AUTO_TEST_SUITE_END()
----

The following table illustrates how different values of `<test_set>` control which test cases ware run.

[%header%autowidth,cols="3*"]
|===
|Description
|Parameter value
|Test cases run

|Run single top-level test case by name
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=test_1
....
a|
....
test_1
....

|Run single nested test case by name
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/suite_1/test_1
....
a|
....
suite_1/suite_1/test_1
....

|Run single test suite by name
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/suite_2
{param_run_test}=suite_1/suite_2/*
....
a|
....
suite_1/suite_2/test_1
suite_1/suite_2/test_2
....

|Run multiple test units that are *siblings* of the same test suite
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/test_1,suite_2
....
a|
....
suite_1/suite_2/test_1
suite_1/suite_2/test_2
suite_1/test_1
....

|Run multiple test units that are not necessarily siblings
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/test_1:test_1
....
a|
....
suite_1/test_1
test_1
....

|Run all tests matching to a given label
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=@L1
....
a|
....
test_1
test_2
suite_1/test_1
....

|Run every test case in the test tree. Note that this will also enable all disabled tests.
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=*
....
a|
....
test_1
test_2
suite_1/suite_1/test_1
suite_1/suite_1/test_2
suite_1/suite_2/test_1
suite_1/suite_2/test_2
suite_1/test_1
suite_1/test_2
suite_1/test_2A
....

|Run every test unit in a given suite with a given prefix
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/test*
....
a|
....
suite_1/test_1
suite_1/test_2
suite_1/test_2A
....

|Run every test unit in a given suite with a given suffix
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/*_1
....
a|
....
suite_1/suite_1/test_1
suite_1/suite_1/test_2
suite_1/test_1
....

|Run every test unit in a given suite with a given infix
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=suite_1/\*_2\*
....
a|
....
suite_1/suite_2/test_1
suite_1/suite_2/test_2
suite_1/test_2
suite_1/test_2A
....

|Run test(s) with given name in any N-level suite
a|
[subs="+macros,+attributes,+quotes"]
....
{param_run_test}=\*/\*/test_2
....
a|
....
suite_1/suite_1/test_2
suite_1/suite_2/test_2
....

|===

For the syntax productions describing the structure of `<test_set>` value see xref:utf_reference/rt_param_reference.adoc#run_test[here].

While using manual absolute test case specification ignores the default run status, it does not ignore the dynamic test dependencies.
If test unit `B` depends on test unit `A` and test `B` is specified to be run by {param_run_test}, `A` is also run, even
if it is not specified, and its failure may cause the execution of `B` to be skipped. Similarly, the failed check of
the {decorator_precondition} may cause the test selected test to be skipped.

// tag reference: doc/modules/ROOT/examples/decorator_21.run-fail.cpp
:bt-name: decorator_21
:bt-rule: run-fail
:bt-descr: run_test and dynamic dependencies
include::partial$bt_example.adoc[]

[#ref_command_line_control_enablers]
=== Relative specification

Term 'relative' in this context means that the configuration is based on either the default run status of the test units or
by the command-line override specified by the _absolute specification_; and atop of this, we additionally either enable
some disabled test units or disable some enabled tests units. The relative specification is controlled by command-line
argument {param_run_test}, with the value using similar syntax as in the absolute specification, but preceded with
either character `'!'` for disabling enabled test units or with character `'+'` for enabling the disabled test units.
This can be summarized with the following table:

[%header%autowidth,cols="3*"]
|===
|command
|specification type
|semantics

a|
[subs="+macros,+attributes,+quotes"]
....
> test_program --{param_run_test}=!<absolute_spec>
....
|disabler
|Enabled test units that match `<absolute_spec>` become disabled.

a|
[subs="+macros,+attributes,+quotes"]
....
> test_program --{param_run_test}=+<absolute_spec>
....
|enabler
|Disabled test units that match `<absolute_spec>` as well as their upstream dependencies become enabled.

|===

The _enabler_ specification is used to enable a set of test units which are initially disabled.

// tag reference: doc/modules/ROOT/examples/decorator_22.run.cpp
:bt-name: decorator_22
:bt-rule: run
:bt-descr: command-line enabler
include::partial$bt_example.adoc[]

Conversely, the _disabler_ specification is used to disable a set of test units which are initially enabled.

// tag reference: doc/modules/ROOT/examples/decorator_23.run.cpp
:bt-name: decorator_23
:bt-rule: run
:bt-descr: command-line disabler
include::partial$bt_example.adoc[]

If there are both an enabler and disabler on one command line that specify the same test, the test becomes disabled. I.e.,
the disabler takes the precedence over the enabler.

[NOTE]
====
While enabler additionally enables the upstream dependencies (introduced with decorator {decorator_depends_on}),
 disabler does not disable them. Therefore when you enable and then disable the same test, you do not disable its upstream dependencies.
====
