= Build scenarios and behaviors
:page-aliases: boost_test/utf_reference/link_references.adoc, boost_test/utf_reference/link_references/config_disable_alt_stack.adoc, boost_test/utf_reference/link_references/config_no_grid_composition.adoc, boost_test/utf_reference/link_references/config_no_random_dataset.adoc, boost_test/utf_reference/link_references/config_no_zip_composition.adoc, boost_test/utf_reference/link_references/link_boost_test_alternative_init_macro.adoc, boost_test/utf_reference/link_references/link_boost_test_dyn_link.adoc, boost_test/utf_reference/link_references/link_boost_test_global_configuration.adoc, boost_test/utf_reference/link_references/link_boost_test_main_macro.adoc, boost_test/utf_reference/link_references/link_boost_test_module_macro.adoc, boost_test/utf_reference/link_references/link_boost_test_no_lib.adoc, boost_test/utf_reference/link_references/link_boost_test_no_main.adoc

[#link_boost_test_main_macro]
== `BOOST_TEST_MAIN`

When defined, this macro creates a stub for the test module initialization (the main entry part). This
macro also expands properly into a `main` function in case the shared library variant of the _Unit Test Framework_ is used.

[CAUTION]
====
This macro should

. be defined before any inclusion directive to _Unit Test Framework_ headers
. be defined exactly for one compilation unit of your test module
====

TIP: The macro xref:{boost_test_module}[`BOOST_TEST_MODULE`] should be preferred

[#link_boost_test_module_macro]
== `BOOST_TEST_MODULE`

Serves the same purpose as the macro xref:{boost_test_main}[`BOOST_TEST_MAIN`] but, in addition, defines the name of the master test suite.

[CAUTION]
====
As xref:{boost_test_main}[`BOOST_TEST_MAIN`], this macro should

. be defined before any inclusion directive to _Unit Test Framework_ headers
. be defined exactly for one compilation unit of your test module
====

An example may be found xref:tests_organization/master_test_suite.adoc#ref_BOOST_TEST_MODULE[here].

[#link_boost_test_alternative_init_macro]
== `BOOST_TEST_ALTERNATIVE_INIT_API`

[WARNING]
====
This macro should be defined before any include directive to the _Unit Test Framework_ headers and is
mutually exclusive with the xref:{boost_test_module}[`BOOST_TEST_MODULE`] macro.
====

In case of custom initialization of the test module entry point, this macro indicates the _Unit Test Framework_ to
use the new API. The differences between the new and old APIs are described in xref:adv_scenarios/obsolete_init_func.adoc[this section].

The way to customize the entry point of the test-module depends on the variant of the _Unit Test Framework_ in use.
Several sections in the documentation are devoted to this:

* xref:adv_scenarios/single_header_customizations.adoc#entry_point[this section] for single header variant,
* xref:adv_scenarios/static_lib_customizations.adoc#init_func[this section] for static link variant,
* xref:adv_scenarios/shared_lib_customizations.adoc#init_func[this section] for shared link variant

[#link_boost_test_no_lib]
== `BOOST_TEST_NO_LIB`

Define this flag to prevent auto-linking.

NOTE: The same flag is used for the _Unit Test Framework_ and the _Program Execution Monitor_ components.

[#link_boost_test_dyn_link]
== `BOOST_TEST_DYN_LINK`

Define this flag to link against the _Unit Test Framework_ shared library.

NOTE: The same flag is used for the _Unit Test Framework_ and the _Program Execution Monitor_ components.

[#link_boost_test_no_main]
== `BOOST_TEST_NO_MAIN`

Prevents the auto generation of the test module initialization functions. This macro is particularly relevant for
manually registered tests in conjunction with dynamic variant of the _Unit Test Framework_. When defined, a `main` function
registering all the tests should be implemented.

An example of a module initialization would be

[source,cpp]
----
#define BOOST_TEST_NO_MAIN
#include <boost/test/unit_test.hpp>

// a function in another compilation unit registering tests under the master test suite.
void register_some_tests_manually(test_suite* test);

bool registering_all_tests()
{
  test_suite* test_master_suite = &boost::unit_test::framework::master_test_suite();
  register_some_tests_manually(test_master_suite);

  // register any other tests function or test suite to the master test suite
  // ...
  return true;
}

int main(int argc, char* argv[])
{
  return ::boost::unit_test::unit_test_main(&registering_all_tests, argc, argv);
}
----

[#link_boost_test_global_configuration]
== `BOOST_TEST_GLOBAL_CONFIGURATION`

Declares a class that will be constructed during the initialization of the test framework, and destructed afterwards.
The framework will not call any other member function than the constructor and destructor.
In particular the constructor and destructor will be called prior and after to the xref:tests_organization/fixtures.adoc#global[global fixtures]
setup and teardown.

This facility is provided to perform additional configuration, in particular programmatic configuration
of the loggers and reporters. See xref:test_output/logging_api.adoc[this section] for more details.

[WARNING]
====
No logging or any other call to the framework assertion is allowed in the constructor and destructor, as its purpose is
 to set-up the loggers/reporters, and the assertions are calling the logging/reporting facility.
 Any such assertion during the execution of the will result in the abortion of the test module .
====

[#config_disable_alt_stack]
== `BOOST_TEST_DISABLE_ALT_STACK`

Disables the support of the alternative stack.

Define this macro before the inclusion of any _Unit Test Framework_ header to disable the support
of the http://www.gnu.org/software/libc/manual/html_node/Signal-Stack.html[alternative stack],
in case your compiler does not support it and the _Unit Test Framework_ cannot automatically guess the lack of support.

See xref:utf_reference/rt_param_reference.adoc#use_alt_stack[`use_alt_stack`] for more details.

[#config_no_random_dataset]
== `BOOST_TEST_NO_RANDOM_DATASET_AVAILABLE`

Indicates that the xref:tests_organization/test_case_generation.adoc#random[random dataset]
is not available.

Unlike the other macros in this section, this one is not defined by you: the _Unit Test Framework_ defines it
for you when the standard library in use provides no `<random>` header, which the random dataset
generator needs. Test it to guard code that would otherwise fail to compile:

[source,cpp]
----
#include <boost/test/data/config.hpp>

#ifndef BOOST_TEST_NO_RANDOM_DATASET_AVAILABLE
// use data::random(...) here
#endif
----

[#config_no_zip_composition]
== `BOOST_TEST_NO_ZIP_COMPOSITION_AVAILABLE`

Indicates that the xref:tests_organization/test_case_generation.adoc#operations[zip operation]
on datasets is not available.

As for `BOOST_TEST_NO_RANDOM_DATASET_AVAILABLE`, the _Unit Test Framework_ defines this macro for you: zipping
datasets needs the `<tuple>` header, and the macro appears when the standard library in use does
not provide one.

[#config_no_grid_composition]
== `BOOST_TEST_NO_GRID_COMPOSITION_AVAILABLE`

Indicates that the xref:tests_organization/test_case_generation.adoc#operations[grid operation]
on datasets is not available.

Defined by the _Unit Test Framework_ under the same condition as
xref:utf_reference/link_references.adoc#config_no_zip_composition[`BOOST_TEST_NO_ZIP_COMPOSITION_AVAILABLE`]:
the grid, or Cartesian product, of two datasets needs the `<tuple>` header.
