= Decorators
:page-aliases: boost_test/tests_organization/decorators.adoc, boost_test/tests_organization/decorators/explicit_decorator_declaration.adoc, boost_test/tests_organization/decorators/suite_level_decorators.adoc

"Decorator" is a uniform mechanism for updating various attributes of the automatically registered test units. These
attributes affect how the test tree is processed during the execution of the test module and include test unit
description, floating-point tolerance and the number of expected failures among others. They are listed in detail in
the following sections.

== Test case decorators

You can apply more than one decorator to the same test unit. A list of decorators is applied to a test case by specifying
it as the second argument to macro xref:{boost_auto_test_case}[`BOOST_AUTO_TEST_CASE`] or the third argument to macro xref:{boost_fixture_test_case}[`BOOST_FIXTURE_TEST_CASE`].

// tag reference: doc/modules/ROOT/examples/decorator_01.run.cpp
:bt-name: decorator_01
:bt-rule: run
:bt-descr: Test unit decorators
include::partial$bt_example.adoc[]

Each decorator in the list is preceded by an asterisk (`+*+`); the subsequent syntax resembles a function call and is
specified in detail for each decorator. If there is more than one decorator in the list, they are concatenated with no
additional separator; each asterisk indicates the beginning of a decorator. In the above example, test case `test_case1`
has one associated _decorator:_ xref:{decorator_label}[`label`]. This means that when test units are filtered based on label, this
test case will match to label `"trivial"`. Test case `test_case2` has three associated decorators: two of type `label`
and one of type `description`.

[#suite_level_decorators]
== Suite-level decorators

Similarly to test case it is possible to apply list of decorators to test suite. It is done by specifying a list of
decorators as the second argument to the macro xref:{boost_auto_test_suite}[`BOOST_AUTO_TEST_SUITE`] or the third argument to the macro
xref:{boost_fixture_test_suite}[`BOOST_FIXTURE_TEST_SUITE`].

// tag reference: doc/modules/ROOT/examples/decorator_02.run.cpp
:bt-name: decorator_02
:bt-rule: run
:bt-descr: Test suite decorators
include::partial$bt_example.adoc[]

How a test suite decorator affects the processing of the test units inside of it varies with the decorator
and is described for each decorator in subsequent sections. For instance, the function of the decorator in the above
example is that when tests are filtered by label `"trivial"`, every test unit in suite `suite1` will be run.

Similar to C++ namespace test suite can be closed and reopened within the same test file or span more than one file
and you are allowed to apply different decorators in each point, where test suite is opened. If this is the case,
the list of decorators applied to the test suite is the union of decorators specified in each place. Here an example.

// tag reference: doc/modules/ROOT/examples/decorator_03.run.cpp
:bt-name: decorator_03
:bt-rule: run
:bt-descr: Decorators on multiple suite openings
include::partial$bt_example.adoc[]

In the above example, the scope of test suite `suite1` is opened three times. This results in a test suite containing
three test cases and associated with two xref:{decorator_label}[`label`] decorators. Therefore running tests by label `"trivial"` as
well as by label `"simple"` both result in executing all three test cases from the suite.

[CAUTION]
====
The above syntax for decorators requires that the compiler supports variadic macros (added in C++11). If you
intend for your test program to also work for compilers without variadic macros, use explicit decorator syntax,
described below.
====

[#explicit_decorator_declaration]
== Explicit decorator declaration

There is another way of associating a decorator set with test units. Macro xref:{boost_test_decorator}[`BOOST_TEST_DECORATOR`] indicates that its set
of decorators is to be applied to the test unit or _test case sequence_ that immediately follows the declaration.

// tag reference: doc/modules/ROOT/examples/decorator_00.run.cpp
:bt-name: decorator_00
:bt-rule: run
:bt-descr: explicit decorator declaration
include::partial$bt_example.adoc[]

In the above example a decorator is applied to a xref:tests_organization/test_case_generation.adoc[data-driven test case]. Macro xref:{boost_data_test_case}[`BOOST_DATA_TEST_CASE`] cannot take the decorator set as one of its arguments, therefore
the explicit decorator declaration is used. Macro xref:{boost_data_test_case}[`BOOST_DATA_TEST_CASE`] generates a sequence of 4 test cases. The
decorator set is applied to each of them.

Another use case for the explicit decorator declaration is when you intend for your test program to compile also on
compilers without variadic macros. In this case it is recommended that you use the more verbose syntax. It is summarized
in the following table:

[%header%autowidth,cols="3*"]
|===
|Test unit to register
|Concise syntax
|Universal syntax

|test case
a|
[source,cpp]
----
BOOST_AUTO_TEST_CASE(test_case, *decor1() *decor2())
{
  // assertions
}
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_AUTO_TEST_CASE(test_case)
{
  // assertions
}
----

|test case with fixture
a|
[source,cpp]
----
BOOST_FIXTURE_TEST_CASE(test_case, Fx, *decor1() *decor2())
{
  // assertions
}
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_FIXTURE_TEST_CASE(test_case, Fx)
{
  // assertions
}
----

|test suite
a|
[source,cpp]
----
BOOST_AUTO_TEST_SUITE(test_suite, *decor1() *decor2())

  // test units

BOOST_AUTO_TEST_SUITE_END()
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_AUTO_TEST_SUITE(test_suite)

  // test units

BOOST_AUTO_TEST_SUITE_END()
----

|test suite with fixture
a|
[source,cpp]
----
BOOST_FIXTURE_TEST_SUITE(test_suite, Fx, *decor1() *decor2())

  // test units

BOOST_AUTO_TEST_SUITE_END()
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_FIXTURE_TEST_SUITE(test_suite, Fx)

  // test units

BOOST_AUTO_TEST_SUITE_END()
----

|data-driven test case
a|
[source,cpp]
----
// not doable
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_DATA_TEST_CASE(test_case, data, var)
{
  // assertions
}
----

|test case template
a|
[source,cpp]
----
// not doable
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_AUTO_TEST_CASE_TEMPLATE(test_case, T, type_list)
{
  // assertions
}
----

|test case template with fixture
a|
[source,cpp]
----
// not doable
----
a|
[source,cpp]
----
BOOST_TEST_DECORATOR(*decor1() *decor2())
BOOST_FIXTURE_TEST_CASE_TEMPLATE(test_case, T, type_list, Fx)
{
  // assertions
}
----

|===

Throughout the reminder of this documentation we use only the concise syntax.
