= Grouping tests into logical units by labels
:page-aliases: boost_test/tests_organization/tests_grouping.adoc

Test-suites and test cases define a hierarchy called the _test tree_, which is useful for organizing tests. These
organization defines an implicit grouping of test unit following the _subtrees_ extracted from the test tree, by just
designing a node on the test tree. Being able to design a group of tests enable, for instance, to execute this group of
test only (covered in xref:runtime_config/test_unit_filtering.adoc[this section]).

However, the subtrees might not reflect all the possible grouping of test units the usage of the test module would
require footnote:[For instance, selecting two siblings without the parent node].

The {utf} provides a flexible way of grouping test units by the use of _labels_, using the decorator
{decorator_label}. It is possible to associate more than one label with a test unit.

Labels can be associated to test cases and test suites. For the latter, the label is inherited by all the nodes in the
subtree defined by the labelled test suite: decorating a test suite with label `L` is equivalent to decorating every test
unit inside with `L`.

[TIP]
====
it is possible to list all labels of a test module from the CLI by using the
 xref:utf_reference/rt_param_reference.adoc#list_labels[`--list_labels`] switch
====

// tag reference: doc/modules/ROOT/examples/decorator_04.run-fail.cpp
:bt-name: decorator_04
:bt-rule: run-fail
:bt-descr: decorator label
include::partial$bt_example.adoc[]
