= Tests naming
:page-aliases: boost_test/tests_organization/test_tree/test_naming.adoc

== Acceptable characters for names

The {utf} is flexible on the naming the test units (test cases/suites) and
it is possible to use a wide variety of characters. However there are scenarios
where the name of a test unit may collide with other features
of the {utf}. For instance:

* a character may collide with specific command line filters for selecting a
subset of the test tree. Among those characters: `'@'`, `'+'` or `'/'`
(see xref:runtime_config/test_unit_filtering.adoc[this section] for
more details)
* a name containing a character that is reserved for the shell/terminal, such as
'!', '\*' ..., may prevent the test name to be passed on the command line *as is*.

To prevent any conflicting declaration, the {utf} *sanitizes* the name given to
a test unit (case or suite), prior to adding the test to the test tree. Any
conflicting character is replaced by an underscore `'_'`.

[NOTE]
====
*Spaces* are not considered as _special chars_ and are preserved, except for the
 leading and trailing spaces which are removed.
====

NOTE: The sanitization of the test unit names has been introduced in xref:change_log.adoc#ref_CHANGE_LOG_3_7[Boost 1.67].

== Constraints on test names

The {utf} considers an error if two sibling test cases have the same name. This consistency check is performed
at runtime and is not sensitive to test filtering.

For test-cases registered automatically, and within the same compilation unit, a compilation error should be raised by
the compiler in case of name conflict.
For manual registration of test cases and in case of conflicts, the too {boost_test_case_name} may be used.

The data driven tests are automatically created in an isolated test-suite and with a name that is indexed on the
sample.

[NOTE]
====
This constraints does not apply to test-suites: Opening/closing a test-suite declaration
 adds the test-cases to an existing or newly created test-suite of that name.
====
