= Managing test dependencies
:page-aliases: boost_test/tests_organization/tests_dependencies.adoc

In general, it is a good practice to write any test as independent as possible from any other, there are however
cases where a dependency cannot be avoided and an order for executing the tests is needed.

In the general setup and for any two test cases `TA` and `TB`, `TB` should not take for granted that `TA` has already
executed, even if `TA` is declared before `TB` in the same translation unit.
The only ordering-related guarantee that _Unit Test Framework_ makes by default is that if test cases `TA` and `TB` are declared in the
same test suite, no test case (call it `TX`) from any other test suite is executed between `TA` and `TB`, even if the
declaration of `TX` appears between the declarations of `TA` and `TB`. In other words, all tests from a suite are
executed in one go, even if the test suite namespace is opened multiple times.

Even though the order is not guaranteed, it may accidentally be preserved across the different runs. In order to make
sure the test cases do not depend on one another, the test module may be called with an additional command-line argument,
xref:utf_reference/rt_param_reference.adoc#random[`random`], to shuffle the tests unit ordering and to be more
robust against an erroneous implicit ordering.

== Declaring a test case dependency

If there exist a dependency between test units, and an ordering is required between the execution of those tests,
it has to be declared explicitly.
Dependencies in the _Unit Test Framework_ affect two dimensions of test units, which are:

* the order of execution of these units
* the execution of a test unit, which is conditioned by the state of its parents

xref:tests_organization/decorators.adoc[Decorator] xref:{decorator_depends_on}[`depends_on`] associates the decorated test case
(call it `TB`) with another test case (call it `TA`) specified by name. This affects the processing the test tree in two
ways:

. first, test case `TA` is ordered to be run before `TB`, irrespective of the order in which they were declared or
added to the test tree,
. second, the execution of `TB` is skipped if `TA` is either disabled or skipped or is executed
and marked as failed.

// tag reference: doc/modules/ROOT/examples/decorator_07.run-fail.cpp
:bt-name: decorator_07
:bt-rule: run-fail
:bt-descr: decorator depends_on
include::partial$bt_example.adoc[]

In the above scenario:

* test case `test3` is run (and fails) because `s1/test1` has been run and succeeded,
* `test4` is skipped because `test3` has failed,
* `test5` is skipped because `s1/test2` is disabled.
