= Test cases
:page-aliases: boost_test/tests_organization/test_cases.adoc

A test case is a unit of execution that is run by the xref:section_glossary.adoc#test_runner[test runner]. It contains instructions and
xref:testing_tools/boost_test_universal_macro.adoc[assertions], and its execution is monitored by the _Unit Test Framework_.
Information about the execution is recorded, and a log/report is produced.

The test runner should be informed of the test case in order to run it: the test case should be *registered* for its
inclusion into the _test tree_.

The _Unit Test Framework_ covers the following test case scenarios:

* *test cases without parameters*: those are similar to the run of a function in the controlled environment of the test runner.
* *test cases with parameters*: this usage is intended to run the same function with potentially many different parameters,
each call with a different parameter being handled by the test runner.
* *test cases on template*: the scenario is to test the same template implementation against several type.

The test case have a different *declaration* APIs for each of the above scenarios. Preferred APIs will declare the test case
and register it automatically in a test tree without a necessity to perform manual registration.

== Manual registration

While automatic registration is preferred test case declaration API, it is also possible to declare tests manually.
For this APIs, _Unit Test Framework_ opted for a least intrusive design based on _generic callback_ approach, which signatures
depends on the king of test case being declared.

The single test module may mix both automated and manual test case
registration. In other words, within the same test module you can have both test cases implemented remotely and
registered manually in the test module initialization function and test cases that are registered automatically at
implementation point.

[CAUTION]
====
The design of manual test case declaration API in _Unit Test Framework_ assumes the test case implementation (test function body)
and test case creation/registration points are remote. As a result you may forget to register the test case
and it's never going to be executed, even though it's present in test file.
====

You need to be sure you exhausted all possible ways to employ automatic registration APIs first before you opt
to use manual registration. Specifically:

* If you need optionally include/exclude some of the test cases, consider using
xref:{decorator_enabled}[`enabled`] _ xref:{decorator_disabled}[`disabled`] _ xref:{decorator_enable_if}[`enable_if`] decorators instead
* If you need to register some parametrized test cases based on some data, consider
xref:tests_organization/test_case_generation.adoc[data-driven] test cases instead
* If you need to specify complicated test unit dependencies, you can use xref:{decorator_depends_on}[`depends_on`]
decorator instead
* if you need to share the logic between the test units consider using
xref:tests_organization/fixtures.adoc[fixtures] instead
