= Acknowledgements
:page-aliases: boost_test/acknowledgments.adoc

== Boost Test Team

Boost.Test 3.0 is being developed and maintained by Gennadiy Rozental and Raffi Enficiaud.

== New documentation

Raffi Enficiaud and Andrzej Krzemienski efforts were a driving force behind the Boost.Test documentation overhaul.

== Second incarnation including the Unit Test Framework

Beman Dawes and Ullrich Koethe started the library. Fernando Cacciola, Jeremy Siek, Beman Dawes, Ullrich Koethe,
Dave Abrahams suggested numerous improvements during the Formal Review. Jeremy Siek was the review manager. Beman
Dawes was a great help in both final testing and merging library with rest of the boost. Gennadiy Rozental was the
developer and maintainer.

== Original Test Library

Ed Brey, Kevlin Henney, Ullrich Koethe, and Thomas Matelich provided very helpful comments during development.
Dave Abrahams, Ed Brey, William Kempf, Jens Maurer, and Wilka suggested numerous improvements during the Formal
Review. Jens Maurer was the review manager. Beman Dawes is the developer and maintainer.
