= Change log
:page-aliases: boost_test/change_log.adoc

Boost.Test releases:

* xref:change_log.adoc#ref_CHANGE_LOG_3_15[Boost.Test v3.15 / boost 1.79]
* xref:change_log.adoc#ref_CHANGE_LOG_3_14[Boost.Test v3.14 / boost 1.74]
* xref:change_log.adoc#ref_CHANGE_LOG_3_13[Boost.Test v3.13 / boost 1.73]
* xref:change_log.adoc#ref_CHANGE_LOG_3_12[Boost.Test v3.12 / boost 1.72]
* xref:change_log.adoc#ref_CHANGE_LOG_3_11[Boost.Test v3.11 / boost 1.71]
* xref:change_log.adoc#ref_CHANGE_LOG_3_10[Boost.Test v3.10 / boost 1.70]
* xref:change_log.adoc#ref_CHANGE_LOG_3_9[Boost.Test v3.9 / boost 1.69]
* xref:change_log.adoc#ref_CHANGE_LOG_3_8[Boost.Test v3.8 / boost 1.68]
* xref:change_log.adoc#ref_CHANGE_LOG_3_7[Boost.Test v3.7 / boost 1.67]
* xref:change_log.adoc#ref_CHANGE_LOG_3_6[Boost.Test v3.6 / boost 1.65]
* xref:change_log.adoc#ref_CHANGE_LOG_3_5[Boost.Test v3.5 / boost 1.64]
* xref:change_log.adoc#ref_CHANGE_LOG_3_4[Boost.Test v3.4 / boost 1.63]
* xref:change_log.adoc#ref_CHANGE_LOG_3_3[Boost.Test v3.3 / boost 1.62]
* xref:change_log.adoc#ref_CHANGE_LOG_3_2[Boost.Test v3.2 / boost 1.61]
* xref:change_log.adoc#ref_CHANGE_LOG_3_1[Boost.Test v3.1 / boost 1.60]
* xref:change_log.adoc#ref_CHANGE_LOG_3_0[Boost.Test v3 / boost 1.59]

[#ref_CHANGE_LOG_3_15]
== Boost.Test v3.15 / boost 1.79

=== New features

=== Bugfixes and feature requests

. {issue-url}/268[#GH-268] Clang warning generated by dataset grid operation in C++20 mode
. {issue-url}/272[#GH-272] Uninitialized memory in `framework_init_observer_t`
. {issue-url}/284[#GH-284] Undefined behavior in `basic_cstring<CharT>::trim_right`
. {issue-url}/297[#GH-297] `BOOST_TEST_GLOBAL_FIXTURE` documentation misleading
. {issue-url}/305[#GH-305] boost test documentation tells users to file bugs with decommissioned Trac.
. {pr-url}/286[#PR-286] fix uninitilized variable in `framework_init_observer_t`
. {pr-url}/301[#PR-301] UB comparing unrelated pointers in `priority_order`
. {pr-url}/275[#PR-275] Replace anonymous `enum` arity with `static constexpr`
. {pr-url}/278[#PR-278] Use `boost_test_print_type` customization point in `lazy_ostream`
. {pr-url}/281[#PR-281] Export `execution_aborted` exception to allow catching it from outside the DLL

[#ref_CHANGE_LOG_3_14]
== Boost.Test v3.14 / boost 1.74

=== New features

* Now able to detect when running under a debugger on macOS/iOS. When running under a debugger, Boost.Test does not
try to catch system errors and the behaviour is the same as if the command line xref:utf_reference/rt_param_reference.adoc#catch_system[`catch_system_error`]
option was set to `no`. Thanks to https://github.com/thughes[Tom Hughes] for this feature.
* Adding support for Embarcadero C++ clang-based compilers, thanks to https://github.com/eldiener[Edward Diener]

=== Bugfixes and feature requests

. {issue-url}/264[#GH-264] GCC suggest-override warnings
. {issue-url}/269[#GH-269] Deprecated bind placeholders in tests
. {pr-url}/142[#PR-142] Make `under_debugger` work on apple (iOS/macOS)
. {pr-url}/266[#PR-266] Changes for Embarcadero C++ clang-based compilers
. {pr-url}/267[#PR-267] Use macOS API only on macOS

[#ref_CHANGE_LOG_3_13]
== Boost.Test v3.13 / boost 1.73

=== New features

* It is now possible to combine tolerance indication, user message and collection comparison modifier in a single `BOOST_TEST` expression
+
`+std::vector<double> v1 = f();
std::vector<double> v2{1.1, 1.19};
BOOST_TEST(v1 == v2, boost::test_tools::tolerance( 1e-3 ) << "comparison to ground truth failed" << boost::test_tools::per_element());+`

=== Bugfixes and feature requests

. {issue-url}/173[#GH-173] Compare collections of floating point values with tolerance
. {issue-url}/179[#GH-179] `test_tools-test` failed on some archs
. {issue-url}/220[#GH-220] Support for cuda `nvcc`
. {issue-url}/221[#GH-221] Coverity security issue (minor) (`umask`)
. {issue-url}/235[#GH-235] Ugly GCC `-Wattributes` warnings that cannot be suppressed using _included_ variant
. {issue-url}/237[#GH-237] Clang-cl's `-Wdelete-non-abstract-non-virtual-dtor` triggered by `test_case_gen`
. {issue-url}/241[#GH-241] warning: comparing floating point with == or != is unsafe `[-Wfloat-equal]`
. {issue-url}/245[#GH-245] code coverity test defect
. {issue-url}/246[#GH-246] Incorrect usage of `BOOST_HEADER_DEPRECATED`
. {issue-url}/251[#GH-251] Context message are always printed if both HRF and Junit loggers are enabled
. {issue-url}/253[#GH-253] Invalid XML log is generated by `BOOST_AUTO_TEST_CASE_TEMPLATE` when tests are skipped
. {issue-url}/254[#GH-254] Console colors are not restored on Windows
. {issue-url}/263[#GH-263] Windows: Header-only mode with multiple translation units requires `BOOST_TEST_NO_LIB`
. {pr-url}/41[#PR-41] Fix: activate virtual destructors for all `msvc` versions
. {pr-url}/114[#PR-114] Silence unreachable code warning in MSVC (`/W4`)
. {pr-url}/187[#PR-187] enable `BOOST_TEST` with tolerance and user-message (through {issue-url}/173[#GH-173])
. {pr-url}/239[#PR-239] Fix unused variable warning in `unit_test_main.ipp`
. {pr-url}/247[#PR-247] Use `+__linux__+` instead of `+__linux+`
. {pr-url}/252[#PR-252] Fix compilation issue due to deleted `std::basic_ostream::operator<<` from `wchar_t`
. {pr-url}/259[#PR-259] Avoid deprecated bind placeholders in global namespace
. {pr-url}/265[#PR-265] Suppress the unused parameter warning for `root_test_unit_id`
. {trac-url}/11107[#11107] A lot of warnings on MSVC due to protected destructor being non-virtual
. {trac-url}/12072[#12072] Lots of `C4265` warnings in test when using Visual Studio 2015 (duplicates {trac-url}/11107[#11107])

[#ref_CHANGE_LOG_3_12]
== Boost.Test v3.12 / boost 1.72

=== New features

* Support for C++17 `std::string_view` has been added.
* Better diagnostic on `boost::exception` and no rtti mode (thanks to Mikhail Pilin / {pr-url}/234[#PR-234])

=== Bugfixes and feature requests

. {issue-url}/206[#GH-206] compile-time disabled test not correctly handled by junit log
. {issue-url}/217[#GH-217] Data test cases fail with `bool` initializer list
. {issue-url}/223[#GH-223] Unable to filter test by name (`-t`, `--run_test`) if template type contains multiple parameters
. {issue-url}/229[#GH-229] Random shuffle deprecated
. {pr-url}/227[#PR-227] Add `printf` format checking attribute to `report_error`
. {pr-url}/231[#PR-231] OpenBSD is missing `SI_ASYNCIO` and `SI_MESGQ`
. {pr-url}/232[#PR-232] fix timeout in windows
. {pr-url}/234[#PR-234] `boost::diagnostic_information()` works in no `rtti` mode

[#ref_CHANGE_LOG_3_11]
== Boost.Test v3.11 / boost 1.71

=== New features

* Now `BOOST_TEST` can be used to compare abstract types

=== Breaking changes

* Marking more headers as deprecated: this might break some compilations
depending on the warning policies.

=== Bugfixes and feature requests

. Fixing a small bug on named timers (Windows only). The bug is visible when
several test modules are executed in parallel on the same machine.
. {issue-url}/209[#GH-209] `BOOST_TEST_CHECK` can't compare abstract classes using gcc
. {issue-url}/218[#GH-218] Default file name (for logger output files)
. {pr-url}/219[#PR-219] Commented out unused argument name (`stack_decorator::apply`)
. {pr-url}/224[#PR-224] Add `BOOST_HEADER_DEPRECATED` to deprecated headers

[#ref_CHANGE_LOG_3_10]
== Boost.Test v3.10 / boost 1.70

=== New features

* New documentation section about xref:runtime_config/runtime_custom.adoc[custom command line]
arguments
* xref:tests_organization/test_case_generation.adoc#dataset_interface[Custom datasets]
are not required to declare a inner type `sample` anymore
* Boost.Test does not depend on Boost.Timer any more (which was pulling also Boost.Chrono
and Boost.System as transitive dependencies).
* Now Boost.Test raises an exception when the test case times-out on Windows. Prior to this release,
times-out on Windows were not failing the test cases. Note that signaling is not available on Windows,
and it is not possible to interrupt a test even in case of time out.
* Time-out now applies to test-suites as well: a test-suite is marked as timed-out if it exceeds the allocated
time. The test units that were not executed at the time-point of the time-out are skipped.
* It is now possible to pass several values for the same context via the tool
{boost_test_context}.
* A new macro {boost_test_info_scope} let define a context for the current scope in a sticky way.
* It is now possible to use xref:testing_tools/floating_point.adoc[floating point]
comparison without being required to cast both operands to floating point types. Now Boost.Test uses floating
point comparisons for expressions such as
+
`BOOST_TEST(3.0001 == 3);`
+
See this section // FIXME(qbk2adoc): unresolved link boost_test.testing_tools.extended_comparison.floating_point.type_promotion_of_the_operands
for more information.

=== Breaking changes

* Boost.Test `minimal.hpp` is now showing a deprecation warning. `minimal.hpp` has been
deprecated for a long time already, and will be removed in the near future. Please
switch to eg. the header only variable of Boost.Test. Tests using `minimal.hpp` can
readily be converted to the header variant. For instance, the following code:
+
`+#include <boost/test/minimal.hpp>
int test_main( int, char *[] )
{
...
}+`
+
may be rewritten as:
+
`+#include <boost/test/included/unit_test.hpp>
BOOST_AUTO_TEST_CASE(test_main)
{
...
}+`
* The floating point comparison behavior change may use this type of comparison while previously
using straight relational operator comparison. In particular this may causes _new warnings_.
* the member function cpp:boost::unit_test::unit_test_log_formatter::log_build_info[boost::unit_test::unit_test_log_formatter::log_build_info] has slightly changed
to accept an additional boolean argument. If you have a custom logger, you will need to update its signature.

=== Bugfixes and feature requests

. {issue-url}/133[#GH-133] Timeout effect on Windows
. {issue-url}/138[#GH-138] expected_failures doesn't work for `BOOST_DATA_TEST_CASE`
. {issue-url}/141[#GH-141] Support for Boost.MP11 and Boost.Hana type lists
. {issue-url}/157[#GH-157] Test name should handle `const`-`volatile` specifiers
. {issue-url}/160[#GH-160] suppress `-Wformat-overflow` when optimization is enabled on GCC 8.2.0
. {issue-url}/174[#GH-174] `UBSAN` identified a problem at exit time by `gcc-8` only
. {issue-url}/176[#GH-176] `[snippet_dataset1_3]` seems to be broken
. {issue-url}/177[#GH-177] `boost_check_equal-str-test` failed on `llvm`
. {issue-url}/180[#GH-180] Unreachable code warning on MSVC builds in test matrix
. {issue-url}/181[#GH-181] `doc_example22` (and `23`) are expected to fail, but do not on clang with release variant builds
. {issue-url}/194[#GH-194] `master_test_suite` declared twice
. {issue-url}/196[#GH-196] junit report: test error is also reported as failure
. {issue-url}/198[#GH-198] Support `BOOST_UNIT_TEST_FRAMEWORK_DYN_LINK` et al
. {issue-url}/199[#GH-199] Runtime `type_mismatch` after upgrade to `1.69`
. {issue-url}/202[#GH-202] `boost/timer.hpp` is deprecated
. {issue-url}/203[#GH-203] Test cases with datasets and fixtures don't support flexible fixture interface
. {issue-url}/204[#GH-204] Feature Request: Allow specifying timeouts for test cases with datasests.
. {issue-url}/208[#GH-208] Incorrect handling of timed-tests on Windows
. {issue-url}/211[#GH-211] `windows.h` should be lower case
. {issue-url}/212[#GH-212] Comment `ar` parameter of `assertion_result` to avoid warning
. {issue-url}/213[#GH-213] `BOOST_SYMBOL_VISIBLE` cannot be used for `enums` with Sun Studio
. {pr-url}/171[#PR-171] Correct library name in test runner help screen
. {pr-url}/172[#PR-172] Check for non-used variables when `NDEBUG` is defined
. {pr-url}/182[#PR-182] fix use of `bind1st` in `example 12`
. {pr-url}/183[#PR-183] remove superfluous semicolon in `example 04`
. {pr-url}/184[#PR-184] fix example to use the correct variable and avoid unused variable warning
. {pr-url}/185[#PR-185] Added CI framework
. {pr-url}/190[#PR-190] fix warning on gcc-7.3 in cygwin claiming `master_test_suite` is declared differently
. {pr-url}/195[#PR-195] Fix MinGW compilation problems
. {pr-url}/197[#PR-197] Feature Request: `BOOST_TEST_CONTEXT` that doesn't require introducing a new scope with braces
. {pr-url}/205[#PR-205] Fix MinGW `vsnprintf` compile errors and warnings
. {pr-url}/214[#PR-214] Fixes an issue with sun_cc lacking the __global attribute for enums
. {trac-url}/7397[#7397] Boost.Test, since boost `1.48` is using the deprecated `Boost.Timer` class (solved via {issue-url}/202[#GH-202])
. {trac-url}/9434[#9434] error: `+namespace boost::timer {}+` re-declared as different kind of symbol (solved via {issue-url}/202[#GH-202])
. {trac-url}/13106[#13106] `libs/test/tools/console_test_runner` does not compile
. {trac-url}/13418[#13418] Request: allow general typelist types in `BOOST_AUTO_TEST_CASE_TEMPLATE()`

[#ref_CHANGE_LOG_3_9]
== Boost.Test v3.9 / boost 1.69

=== New features

* Official support of header-only variant of Boost.Test with multiple translation units. This feature
was available but needed to be properly documented (xref:adv_scenarios/single_header_customizations.adoc#multiple_translation_units[here]
and xref:usage_variants.adoc[here]).
* It is now possible to manually add a test case by specifying its name, with {boost_test_case_name}
* Better logging of messages in `boost::exception`

=== Bugfixes and feature requests

. {issue-url}/149[#GH-149] Setting color_output=no does not disable the output of color format codes
. {issue-url}/150[#GH-150] Some headers fail to compile independently
. {issue-url}/156[#GH-156] `close_at_tolerance` always returns `false` for comparisons of infinity
. {issue-url}/158[#GH-158] Detecting `boost_test_print_type` does not work when testing a type with an explicit conversion to `bool`
. {issue-url}/163[#GH-163] Significant start slowdown on MSVC x64/Debug after upgrade to `v1.68.0`
. {pr-url}/147[#PR-147] Catch block for `boost::exception` appears after `std::exception` in `execution_monitor::execute()`
. {pr-url}/148[#PR-148] Colored output contradiction
. {pr-url}/151[#PR-151] Fix warning: `BOOST_CLANG` is not defined, evaluates to `0`
. {pr-url}/154[#PR-154] When specifying `--color_output=no`, don't output color codes
. {pr-url}/161[#PR-161] add a self-containment test
. {trac-url}/13380[#13380] data-driven tests' join operator `+` corrupts first column (duplicates {trac-url}/12216[#12216])
. {trac-url}/13625[#13625] Boost.test fail to compile with `-Werror=missing-declarations` on some architectures
. {trac-url}/13637[#13637] Fix for Bug {trac-url}/12597[#12597] causes a problem with `BOOST_TEST_CASE`

[#ref_CHANGE_LOG_3_8]
== Boost.Test v3.8 / boost 1.68

=== New features

* The tests generated from a dataset are now instantiated during the framework setup. This
let the dataset generator access the `argc` and `argv` of the master test suite. For indicating
a dataset that should be instantiated in a delayed manner, a new `data::make_delayed` helper has
been introduced.
* It is now possible to create a dataset with `data::make`, with variable number of arguments.
As the datasets are monomorphic, it should be possible to cast all elements to the first element type.

=== Breaking changes

* the xref:tests_organization/master_test_suite.adoc[`master_test_suite_t`] is not copyable anymore.
* As datasets can now be delayed, it might be that additional copies of the dataset arguments are performed.
This is especially the case for datasets created out of an `std::initializer_list`.

=== Bugfixes and feature requests

. {pr-url}/143[#PR-143] Fix exception_api.run-fail.cpp doc example
. {pr-url}/145[#PR-145] Fix build of library on recent Cygwin editions
. {trac-url}/12095[#12095] disabling test with precondition leads to error
. {trac-url}/12953[#12953] access to `+master_test_suite().{argc, argv}+`
. {trac-url}/13504[#13504] `[Boost::Test]` short form of `catch_system_errors` not working
. {trac-url}/13525[#13525] Boost Test 1.67.0: Compilation error with GCC 4.6.3
. {trac-url}/13528[#13528] Boost Test 1.67 crashes when the `--report_sink` command-line parameter is used

[#ref_CHANGE_LOG_3_7]
== Boost.Test v3.7 / boost 1.67

=== Breaking changes

* Now colour is on by default for the output streams that are either `std::cout` or `std::cerr`. This can be
disabled by passing xref:utf_reference/rt_param_reference.adoc#color_output[`--no_color_ouput`] (or just `--no_color`)
to the command line.
* Adding test cases with the same name to the same test suite is reported as an error. This impacts
xref:tests_organization/test_organization_templates.adoc[template] and
xref:tests_organization/param_test.adoc[parametrized] test cases, as well as manually
registered tests. Make sure you have no duplicate names.

=== New features

* Colour output on Windows
* Improved and clearer command line help
* `BOOST_AUTO_TEST_CASE_TEMPLATE` now accepts a sequence of types in an `std::tuple`

=== Bugfixes and feature requests

. {pr-url}/112[#PR-112] Deliberate-failure tests shouldn't be optimized
. {pr-url}/118[#PR-118] Update VxWorks support
. {pr-url}/118[#PR-118] `[clang]` Fix `[-Wc++11-narrowing]` error
. {pr-url}/121[#PR-121] fix compiler warning
. {pr-url}/122[#PR-122] Fix some fallthrough warnings with `gcc >= 7`
. {pr-url}/125[#PR-125] Prevent 2 unused parameter warnings
. {pr-url}/127[#PR-127] Silence 'unused variable' warning
. {pr-url}/134[#PR-134] Fix `stdcerr` file creation on shutdown
. {pr-url}/136[#PR-136] Change `Windows.h` include to all-lowercase (MinGW)
. {trac-url}/12092[#12092] Request: allow `std::tuple` typelists in `BOOST_AUTO_TEST_CASE_TEMPLATE`
. {trac-url}/12596[#12596] Sanitize metacharacters in test names
. {trac-url}/12597[#12597] Report tests with clashing names
. {trac-url}/12969[#12969] Problem linking `print_helper_t<nullptr_t>` under Clang
. {trac-url}/13058[#13058] `errors.hpp` in Boost Test requires warning `C4946` to be `off`
. {trac-url}/13149[#13149] Dependency decorators on parent suites
. {trac-url}/13170[#13170] `BOOST_AUTO_TEST_CASE_TEMPLATE` don't want `typedef` for list
. {trac-url}/13181[#13181] Boost test can't compare classes which have `begin` and `end` but not `const_iterator`
. {trac-url}/13371[#13371] Use-after-free with `--log_sink=file`
. {trac-url}/13387[#13387] Test header fails to compile
. {trac-url}/13398[#13398] Log format JUNIT generates invalid XML files
. {trac-url}/13407[#13407] Boost.Test appears to crash under Cygwin
. {trac-url}/13435[#13435] `BOOST_TEST_GLOBAL_CONFIGURATION` (result report shutdown time)
. {trac-url}/13443[#13443] Boost.Test data driven test fails to compile when number of samples greater than 9

[#ref_CHANGE_LOG_3_6]
== Boost.Test v3.6 / boost 1.65

=== Breaking changes

* {boost_global_fixture} is flagged as deprecated and will be removed in a later version
* Using test assertions and macros is not allowed when used inside {boost_global_fixture}. Please use {boost_test_global_fixture}
instead (see below).
* the interface for loggers has slightly changed to take into account the current log level. This is for addressing {trac-url}/12631[#12631].

=== New features

* VS2017 / C++17 compatibility (thanks to Daniela Engert)
* Deprecating {boost_global_fixture} in favor of {boost_test_global_fixture} and {boost_test_global_configuration}. This
helps separating the logic of the fixtures associated to the master test suite, from the one used for setting up the logging
and reporting facility, and results in a general cleaner design.
* It is possible to use now the {boost_test} check to comparing a collection with respect to regular arrays. See
xref:testing_tools/collections.adoc#ref_boost_test_coll_c_arrays[this section] for more details.

=== Bugfixes and feature requests

. {pr-url}/106[#PR-106] replace deprecated binders and adapters, and `random_shuffle` by more modern equivalents
. {trac-url}/5282[#5282] Test fixtures do not support virtual inheritance
. {trac-url}/5563[#5563] using a test macro in a global fixture crashes Boost.Test
. {trac-url}/11471[#11471] array is a sequence
. {trac-url}/11962[#11962] `BOOST_TEST_MESSAGE` in fixture constructor - invalid XML
. {trac-url}/12228[#12228] Some test headers fail to compile independently
. {trac-url}/12631[#12631] `BOOST_TEST_MESSAGE` generates incorrect output when used in `BOOST_DATA_TEST_CASE`
. {trac-url}/13011[#13011] `BOOST_TEST` broken with floating point relational operators

[#ref_CHANGE_LOG_3_5]
== Boost.Test v3.5 / boost 1.64

=== New features

* Now Boost.Test provides xref:test_output/test_tools_support_for_logging.adoc#ref_log_output_custom_customization_point[customization points] for logging user defined types:
this solution is less intrusive than forcing the definition of `operator<<` for a specific type.
* xref:test_output/log_formats.adoc#log_junit_format[JUnit output format] can now have a
xref:test_output/log_formats.adoc#test_log_output[log-level] set between `success` and
`non-fatal error`, and defaults to `general information`.
* xref:test_output/log_formats.adoc#log_junit_format[JUnit output format] is now more
efficient in case a lot of checks are done in a test module.

=== Bugfixes and feature requests

. {pr-url}/107[#PR-107] `BOOST_NO_EXCEPTIONS` typo making `throw_exception` unusable under some circumstances
. {pr-url}/108[#PR-108] Change capital variable names to lowercase
. {trac-url}/11756[#11756] boost.Test: non standards compliant use of `+FE_*+` macros (unable to compile boost test library on FPU-less arches) (reopened)
. {trac-url}/12540[#12540] Provide customization point for printing types in tests
. {trac-url}/12712[#12712] `BOOST_AUTO_TEST_SUITE`: Generate unique names by using `+__COUNTER__+`
. {trac-url}/12748[#12748] Boost.Test defines a variable called `VERSION`
. {trac-url}/12778[#12778] Boost.Test is broken against left shift operator in certain cases (`nullptr` issue)

[#ref_CHANGE_LOG_3_4]
== Boost.Test v3.4 / boost 1.63

=== Breaking changes

. Now colons that appear in test case names are replaced with underscores. This affect mainly the
xref:tests_organization/test_organization_templates.adoc[template/typed test cases].
The change is needed since the colon '`:`' is interpreted as a filter separators since 1.62, and it is
otherwise not possible to execute the tests reported by `--list_content`. See {trac-url}/12531[#12531] for more details.

=== New features

* Now xref:testing_tools/collections.adoc#boost_test_coll_perelement[`per_element`] and xref:testing_tools/collections.adoc#boost_test_coll_default_lex[`lexicographic`] modifiers of {boost_test}
can also be applied to string comparison. See
xref:testing_tools/strings.adoc[string comparison] for more details.

=== Bugfixes and feature requests

. {pr-url}/103[#PR-103] Syntactic change silences latest gcc warnings
. {pr-url}/105[#PR-105] Fix unused parameter warnings/errors with gcc 6
. {trac-url}/11756[#11756] boost.Test: non standards compliant use of `+FE_*+` macros (unable to compile boost test library on FPU-less arches)
. {trac-url}/11907[#11907] Why does `BOOST_TEST()` treat `std::string` as a collection?
. {trac-url}/12339[#12339] Propose users given way to disable blink in colour output
. {trac-url}/12506[#12506] typo in Boost.test `report_sink` description
. {trac-url}/12507[#12507] Boost.test `--report_sink` parameter broken
. {trac-url}/12530[#12530] No way to find out Boost.Test version without running any tests
. {trac-url}/12531[#12531] `--run_test` in Boost 1.62 does not accept test names which contain ':'

[#ref_CHANGE_LOG_3_3]
== Boost.Test v3.3 / boost 1.62

=== New features

* Boost.Test now treats each sample of a dataset test case as being a uniquely named test case under the same test suite,
which enables the (re)run of one particular sample from the command line interface. See
here // FIXME(qbk2adoc): unresolved link boost_test.tests_organization.test_cases.test_case_generation.datasets_auto_registration.samples_and_test_tree
for more details,
* Boost.Test learned to interpret ':' as a separator for the test filters: the string passed to
xref:utf_reference/rt_param_reference.adoc#run_test[`--run_test`]
generates tokens as if `--run_test` has been repeated, which enables the set up of several test filters
through the associated environment variable `BOOST_TEST_RUN_FILTERS`
* the {utf} learned to log the messages in the xUnit/JUNIT log format.
See xref:test_output/log_formats.adoc#log_junit_format[here] for more details.
* the {utf} learned to have several loggers at the same time, each of which with their own log level and log sink.
See the associated command line switch xref:utf_reference/rt_param_reference.adoc#logger[`--logger`] and
corresponding environment variable `BOOST_TEST_LOGGER` for more details.
* loggers are now able to indicate their default output stream and log level.

=== Bugfixes and feature requests

. {pr-url}/81[#PR-81] Possibility to remove the support of the alternative stack at compilation time. See
xref:utf_reference/link_references.adoc#config_disable_alt_stack[`BOOST_TEST_DISABLE_ALT_STACK`] for more details.
. {trac-url}/8707[#8707] Provide Standard xUnit XML Output from Boost Test
. {trac-url}/8834[#8834] Boost Test should be able to generate report in both XML and HRF together
. {trac-url}/11128[#11128] `[bb10/qnx failures]` Build error
. {trac-url}/11845[#11845] Ability to generate the unique and stable test name for every data set in `BOOST_DATA_TEST_CASE`
. {trac-url}/11859[#11859] Wrong handling of "," in Run-Parameters
. {trac-url}/12024[#12024] boost test depends on nonexisting `+abi::__cxa_demangle+` on android
. {trac-url}/12093[#12093] Boost 1.60.0: Build fails (gcc 4.6)
. {trac-url}/12103[#12103] Fix for gcc bug 58952 (`getchar()` is defined as a macro in `uClibc`)
. {trac-url}/12224[#12224] Crash on MSVC with RTTI disabled
. {trac-url}/12241[#12241] Data-driven testing over a range of `std::tuple` has broken
. {trac-url}/12257[#12257] Incorrect line numbers in `test_units` generated from `test_case_gen`
. {trac-url}/12378[#12378] Compilation errors with clang 3.8

[#ref_CHANGE_LOG_3_2]
== Boost.Test v3.2 / boost 1.61

=== New features

* now datasets support any xref:tests_organization/test_case_generation.adoc#datasets[arity], using the
variadic template support of the compiler.
* now datasets support fixtures through `BOOST_DATA_TEST_CASE_F`, see
xref:tests_organization/test_case_generation.adoc#datasets[here] for more details
* now datasets honors move semantics of the types used for samples

=== Bugfixes and feature requests

. {trac-url}/6767[#6767] Use of namespace qualifier with floating point exception functions breaks if they are macros
. {trac-url}/8905[#8905] `boost/test/impl/debug.ipp`: Ignores return value from `WaitForSingleObject`
. {trac-url}/9443[#9443] Runtime parameter Random seed for random order of test cases not respected correctly
. {trac-url}/11854[#11854] Add fixture support in `BOOST_DATA_TEST_CASE`
. {trac-url}/11887[#11887] `BOOST_TEST(3u == (std::max)(0u, 3u))` fails
. {trac-url}/11889[#11889] `BOOST_DATA_TEST_CASE` fails to compile for 4D and higher dimensional grids
. {trac-url}/11983[#11983] Boost Test XML Report contains unescaped XML characters

[#ref_CHANGE_LOG_3_1]
== Boost.Test v3.1 / boost 1.60

=== New major features

* improved API for datasets
** it is now possible to use initializer lists
** the use of `make` as top left dataset is not necessary anymore
* improved command line interface
** clearer help commands
** now proposes closest matching command in case of ambiguity
** reports invalid or ambiguous parameters: this might break existing calls when user defined commands are
provided to the test module. The following calling convention should be adopted:
*** if the test module uses user supplied commands, those should be passed after an empty token `--`
*** all boost.test related commands should be passed before `--`, if any
+
Example:
the call
`test_module --user-arg1=xy --log_level=test_suite`
should be rewritten to
`test_module --log_level=test_suite -- --user-arg1=xy`

=== Bugfixes and feature requests

. {trac-url}/3384[#3384] Double-quoted arguments including spaces are divided by Boost.Test.
. {trac-url}/3897[#3897] Test framework does not include `<osreldate.h>` before testing `+__FreeBSD_version+` (fixed in 1.59)
. {trac-url}/6032[#6032] Program options within `init_unit_test_suite` are incorrect when using path and whitespaces
. {trac-url}/6859[#6859] Boost.Test eats away last empty command line parameter
. {trac-url}/7257[#7257] Boost.Test alters and does not restore `ostream` precision after any Test macro (fixed in 1.59)
. {trac-url}/9228[#9228] Patch to make Boost.Test work with RTTI disabled (fixed in 1.59)
. {trac-url}/10317[#10317] boost::test corrupts contents of `argv` if a paramter contains whitespace
. {trac-url}/11279[#11279] invalid parameters should be reported
. {trac-url}/11478[#11478] Boost Test Exception Assert Failure has poor message
. {trac-url}/11571[#11571] Can't compile `BOOST_TEST( ..., per_element() )` comparison of `vector<string>`
. {trac-url}/11623[#11623] Clang rejects some simple `BOOST_TEST()` statements
. {trac-url}/11624[#11624] `BOOST_TEST( 0.0 == 0.0 )` fails under C++11 (GCC and Clang)
. {trac-url}/11625[#11625] `BOOST_TEST( ..., per_element() )` erroneously requires collections are comparable

[#ref_CHANGE_LOG_3_0]
== Boost.Test v3 / boost 1.59

=== New major features

* {boost_test} generic assertion
* xref:tests_organization/test_case_generation.adoc[data driven test cases]: supersedes the parametric test case (unary test cases)
* test units xref:tests_organization/decorators.adoc[attributes], that allow finer control over test units property and behavior
* logical grouping of the test units using xref:tests_organization/tests_grouping.adoc[labels]
* support for declaring xref:tests_organization/tests_dependencies.adoc[dependencies] over test cases
* attributes for xref:tests_organization/enabling.adoc[enabling or disabling] test execution based on static, compile-time or runtime rules
* extended xref:runtime_config/test_unit_filtering.adoc[unit test filtering] from the command line (negation, labels, ...)
* color output with xref:utf_reference/rt_param_reference.adoc#color_output[`color_output`]
* test bed listing with xref:utf_reference/rt_param_reference.adoc#list_content[`list_content`]
* rewritten documentation using quickbook

=== Bugfixes and feature requests

. {trac-url}/2018[#2018] Error in the documentation chapter "Runtime parameters reference"
. {trac-url}/2450[#2450] equations in Floating-point comparison algorithms html are not rendered properly
. {trac-url}/2600[#2600] Unit Test Framework - missed documentation
. {trac-url}/2717[#2717] `BOOST_<level>_EQUAL_COLLECTION` docs typo
. {trac-url}/2759[#2759] Typos in test new-year-resolution.html
. {trac-url}/3182[#3182] `+_CrtSetReportFile+` can be used to redirect memory leaks report
. {trac-url}/3316[#3316] Access violation when trying to log from `init_tests_func`
. {trac-url}/3392[#3392] Boost::Test: Wrong contents for documentation of the `BOOST_TEST_PASSPOINT` macro
. {trac-url}/3402[#3402] Invalid define name in documentation (duplicates #{trac-url}/2717[#2717])
. {trac-url}/3445[#3445] incorrect link in the docs
. {trac-url}/3463[#3463] `GT` is GREAT!
. {trac-url}/3542[#3542] Bug in documentation of detect_memory_leak parameter (duplicates #{trac-url}/2018[#2018])
. {trac-url}/3481[#3481] Boost Testing doesn't work under Sun Solaris Containers (duplicates #{trac-url}/3592[#3592])
. {trac-url}/3495[#3495] Boost::Test enters endless loop when running in `vserver` environment (duplicates #{trac-url}/3592[#3592])
. {trac-url}/3592[#3592] under_debugger() goes into infinite loop
. {trac-url}/3595[#3595] Typo (duplicates #{trac-url}/2759[#2759])
. {trac-url}/3623[#3623] Boost Test Typo (duplicates #{trac-url}/2759[#2759])
. {trac-url}/3664[#3664] `SIGCHLD` always considered fatal error
. {trac-url}/3784[#3784] Documentation errors in Execution Monitor Compilation
. {trac-url}/3785[#3785] Documentation errors in Program Execution Monitor implementation
. {trac-url}/3811[#3811] global namespace pollution
. {trac-url}/3834[#3834] doc: probably incorrect HTML rendering (duplicates #{trac-url}/2450[#2450])
. {trac-url}/3896[#3896] erroneous documentation in boost test command line parameter description
. {trac-url}/3932[#3932] Error in `BOOST_<level>_GT` description (duplicates #{trac-url}/3463[#3463])
. {trac-url}/3938[#3938] doc: incorrect macro name (duplicates #{trac-url}/2759[#2759])
. {trac-url}/3964[#3964] Documentation for `BOOST_<level>_CLOSE_FRACTION` is incorrect
. {trac-url}/3978[#3978] Failed to completely redirect TestLog to file, bugfix appended
. {trac-url}/3979[#3979] `<boost/test/exception_safety.hpp>` requires additional includes
. {trac-url}/4161[#4161] spelling mistakes...
. {trac-url}/4275[#4275] Documentation error Boost.Test (duplicates #{trac-url}/2717[#2717])
. {trac-url}/4389[#4389] Enable boost_test to run specific tests with any required dependent tests.
. {trac-url}/4434[#4434] `BOOST_AUTO_EST_CASE` typos in docs
. {trac-url}/4587[#4587] Broken link in website
. {trac-url}/4806[#4806] Invalid link (examples not showing up in documentation)
. {trac-url}/4911[#4911] ENH: boost.test output the exception real type name.
. {trac-url}/4923[#4923] Missing semicolon in documentation example
. {trac-url}/4924[#4924] Minor typo in Boost::Test docs
. {trac-url}/4982[#4982] Boost.Test has misspelled Gennadiy Rozental e-mail address
. {trac-url}/5008[#5008] Boost.Test does not do check-pointing of entry/exit of test cases
. {trac-url}/5036[#5036] Boost.Test VC memory leak report should direct to `stderr`
. {trac-url}/5262[#5262] Run tests by name utility doesn't support negation
. {trac-url}/5374[#5374] Errors from Boost.Test are no more shown in the Error list in VS2010
. {trac-url}/5412[#5412] XML formatter in test library processes strings with subsequences `]]>` incorrectly
. {trac-url}/5563[#5563] using a test macro in a global fixture crashes Boost.Test
. {trac-url}/5582[#5582] There is a memory leak in the `BOOST_AUTO_TEST_CASE_TEMPLATE`
. {trac-url}/5599[#5599] boost::test documentation gives poor instruction
. {trac-url}/5718[#5718] broken link to unit testing framework examples
. {trac-url}/5729[#5729] Missing static_cast in fpt_limits
. {trac-url}/5870[#5870] The warning stack is not maintained
. {trac-url}/5972[#5972] Support program option to only dump the test-tree in text to output stream
. {trac-url}/6002[#6002] Failed to completely redirect TestLog to file (duplicates)
. {trac-url}/6071[#6071] Boost Test (Boost 1.46.0) GCC 4.6.1 error: ambiguous overload for ‘operator’
. {trac-url}/6074[#6074] warnings-as-errors not usable with Boost.test in release mode
. {trac-url}/6161[#6161] SunOS: bad `putenv` declaration (duplicates {trac-url}/6766[#6766])
. {trac-url}/6766[#6766] incorrect declaration for `putenv` in `config.hpp`
. {trac-url}/6712[#6712] Eliminate warnings with GCC
. {trac-url}/6748[#6748] Link in the documentation points to wrong page
. {trac-url}/7046[#7046] Output full error message, not just 512 chars
. {trac-url}/7136[#7136] Correct documentation for `BOOST_<level>_CLOSE_FRACTION` is not reflected into released documents
. {trac-url}/7410[#7410] Test Units (Cases and Suites) in Boost.Test do not capture `+__FILE__+` and `+__LINE__+` at declaration point making it impossible to provide source file linking using external test management tools
. {trac-url}/7894[#7894] Boost.Test documentation contains no linking instructions
. {trac-url}/8201[#8201] Broken link in document
. {trac-url}/8272[#8272] `BOOST_REQUIRE_CLOSE` fails to compile with `boost::multiprecision::cpp_dec_float_100` (duplicates #{trac-url}/11054[#11054])
. {trac-url}/8467[#8467] Incorrect link in document (duplicates #{trac-url}/6748[#6748])
. {trac-url}/8679[#8679] Boost.Test pollutes boost namespace with it's own `enable_if/disable_if` templates
. {trac-url}/8862[#8862] Boost.Test typo in documentation
. {trac-url}/8895[#8895] English error in test collection comparison
. {trac-url}/9179[#9179] Documentation: broken link (unable to find =const_string.hpp/const_string_test.cpp=)
. {trac-url}/9272[#9272] boost::test `BOOST_<level>_GT` documentation bug (duplicates #{trac-url}/3463[#3463])
. {trac-url}/9390[#9390] Incomplete `BOOST_TEST_DONT_PRINT_LOG_VALUE`
. {trac-url}/9409[#9409] Some source code examples are missing
. {trac-url}/9537[#9537] const_string_test example fails
. {trac-url}/9539[#9539] Floating-point comparison algorithms aren't formatted correctly
. {trac-url}/9581[#9581] Squassabia reference link gives 404 not found
. {trac-url}/9960[#9960] Warnings on Clang
. {trac-url}/10256[#10256] \[boost test] - issue: `sigaltstack`
. {trac-url}/10318[#10318] Minor documentation fix
. {trac-url}/10394[#10394] Broken links in Boost Test documentation
. {trac-url}/10888[#10888] Assertion failures don't show up in the errors pane in VS 2010, VS 2012 or VS 2013 (duplicates)
. {trac-url}/11054[#11054] Floating-point comparison of multiprecision values fails if expression template is on
. {trac-url}/11347[#11347] `DS` identifier causes test failures in `+doc/examples/dataset_example*.cpp+`
. {trac-url}/11358[#11358] Boost.Test v3 warning could helpfully be suppressed.
. {trac-url}/11359[#11359] `BOOST_CHECK_EQUAL_COLLECTIONS`: can't control output operator (duplicates #9390)
. {trac-url}/11425[#11425] use-of-uninitialized-value (obsolete)
