= Glossary
:page-aliases: boost_test/section_glossary.adoc

Here is the list of terms used throughout this documentation.

[#ref_test_module]
== Test module

This is a single binary that performs the test. Physically a test module consists of one or more test source files,
which can be built into an executable or a dynamic library. A test module that consists of a single test source
file is called _single-file test module_. Otherwise
it's called _multi-file test module_. Logically, each test module consists of four parts:

. xref:section_glossary.adoc#test_setup[test setup] (or test initialization),
. xref:section_glossary.adoc#test_body[test body]
. xref:section_glossary.adoc#test_cleanup[test cleanup]
. xref:section_glossary.adoc#test_runner[test runner]

The test runner part is optional. If a test module is built as
an executable, the test runner is built-in. If a test module is built as a dynamic library, it is run by an
xref:adv_scenarios/external_test_runner.adoc[external test runner].

WARNING: The test module should have at least one test-case defined, otherwise it is considered as an error.

[#test_body]
== Test body

This is the part of a test module that actually performs the test.
Logically test body is a collection of xref:section_glossary.adoc#test_assertion[test assertions] wrapped in
xref:section_glossary.adoc#test_case[test cases], which are organized in a xref:section_glossary.adoc#ref_test_tree[test tree].

[#ref_test_tree]
== Test tree

This is a hierarchical structure of xref:section_glossary.adoc#test_suite[test suites] (non-leaf nodes) and
xref:section_glossary.adoc#test_case[test cases] (leaf nodes). More details can be found xref:tests_organization/index.adoc[here].

[#ref_test_unit]
== Test unit

This is a collective name when referred to either a xref:section_glossary.adoc#test_suite[test suite] or
xref:section_glossary.adoc#test_case[test cases]. See xref:tests_organization/index.adoc[this section] for more details.

[#test_assertion]
== Test assertion

This is a single binary condition (binary in a sense that is has two outcomes: pass and fail) checked
by a test module.

There are different schools of thought on how many test assertions a test case should consist of. Two polar
positions are the one advocated by TDD followers - one assertion per test case; and opposite of this - all test
assertions within single test case - advocated by those only interested in the first error in a
test module. The {utf} supports both approaches.

[#test_case]
== Test case

This is an independently monitored function within a test module that
consists of one or more test assertions. The term _independently monitored_ in the definition above is
used to emphasize the fact, that all test cases are monitored independently. An uncaught exception or other normal
test case execution termination doesn't cause the testing to cease. Instead the error is caught by the test
case execution monitor, reported by the {utf} and testing proceeds to the next test case. Later on you are going
to see that this is on of the primary reasons to prefer multiple small test cases to a single big test function.

[#test_suite]
== Test suite

This is a container for one or more test cases. The test suite gives you an ability to group
test cases into a single referable entity. There are various reasons why you may opt to do so, including:

* To group test cases per subsystems of the unit being tested.
* To share test case setup/cleanup code.
* To run selected group of test cases only.
* To see test report split by groups of test cases.
* To skip groups of test cases based on the result of another test unit in a test tree.

A test suite can also contain other test suites, thus allowing a hierarchical test tree structure to be formed.
The {utf} requires the test tree to contain at least one test suite with at least one test case. The top level
test suite - root node of the test tree - is called the master test suite.

[#test_setup]
== Test setup

This is the part of a test module that is responsible for the test
preparation. It includes the following operations that take place prior to a start of the test:

* The {utf} initialization
* Test tree construction
* Global test module setup code
* _Per test case_ setup code, invoked for every test case it's assigned to, is also attributed to the
test initialization, even though it's executed as a part of the test case.

[#test_cleanup]
== Test cleanup

This is the part of test module that is responsible for cleanup operations.

[#test_fixture]
== Test fixture

Matching setup and cleanup operations are frequently united into a single entity called test fixture.

[#test_runner]
== Test runner

This is an _orchestrator_ or a _driver_ that, given the test tree, ensures the test tree is initialized, tests are executed and necessary reports generated. For more information xref:adv_scenarios/test_module_runner_overview.adoc[see here].

[#test_log]
== Test log

This is the record of all events that occur during the testing.

[#test_report]
== Test report

This is the report produced by the {utf} after the testing is completed, that indicates which test cases/test
suites passed and which failed.
