= The external test runner usage variant
:page-aliases: boost_test/adv_scenarios/external_test_runner.adoc

This usage variant does not provide any xref:adv_scenarios/test_module_runner_overview.adoc[test runner].
You employ it when you only want to define a xref:section_glossary.adoc#ref_test_tree[test tree] and possibly an
xref:adv_scenarios/test_module_init_overview.adoc[initialization function],
and expect another (external) program to evaluate these tests. This external program will come with its own test runner.

If you plan to use an external test runner with your test module, you need to build it as a dynamic library.
You need to define macro flag {boost_test_dyn_link} either in a makefile or before the header
`boost/test/unit_test.hpp` inclusion. An external test runner utility is required to link with dynamic library.

The {utf} comes with an example external test runner `console_test_runner`:
Given a name of the test module (implemented as a shared library), and a name of the initialization function defined therein,
the program can run all the tests from the module's test tree.
