= Advanced Usage Scenarios
:page-aliases: boost_test/adv_scenarios.adoc

If you are reading this chapter, this means that the wide range of tools and interfaces covered
in the previous sections are not sufficient for the testing scenario
you have in mind. You are here to bend the {utf} to your will and ... we are not going to
stop you. Instead we'll try to guide you so that some dark corners do not look scary.

In most cases the {utf} is going to be supplied for you either as part of your system libraries
or set of libraries used by your companies. Yet if you are facing the necessity to build your
own static or dynamic library of the {utf} or need to customize the build for any reason, section
xref:adv_scenarios/build_utf.adoc[Building the {utf}] covers all the necessary steps.

To streamline the experience of setting up your test module, the {utf} provides some default
initialization logic for them. Usually the default test module initialization will work just fine,
but if you want to implement some custom initialization or change how default initialization
behaves you need to first look in *Test module initialization* section. Here you'll learn
about various options the {utf} provides for you to customize this behavior.

The part of the framework which loads, initializes and executed your test module is called the
*Test Runner*. Each usage variant comes with default test runner. If, instead, you prefer to
implement your own entry point into the test module (for example if you need to implement the
`main` function yourself and not use the one provided by the {utf}, you need to learn about
{utf} interfaces involved in test runners operations. These are covered in the *Test runners*
section. Let me reiterate that you only need to this section if regular regular options for
customization of initialization logic like
xref:tests_organization/fixtures.adoc[fixtures] or xref:tests_organization/decorators.adoc[decorators]
are not sufficient for your purposes.
