= Shared-library variant customizations
:page-aliases: boost_test/adv_scenarios/shared_lib_customizations.adoc

[CAUTION]
====
Macro {boost_test_dyn_link} (which instructs the compiler/linker to dynamically link against a shared
library variant) may be implicitly defined when macro `BOOST_ALL_DYN_LINK` is defined.
====

[CAUTION]
====
In order to be able to run a test built with the dynamic variant, the operating system should be able
 to find the dynamic library of the {utf}. This means, for example on Linux and MacOSX respectively, setting the environment
 variable `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` properly prior to the execution of the test module.
====

[#entry_point]
== Customizing the module's entry point

In this variant, in one of the source files, you now have to define your custom entry point, and invoke the default
xref:adv_scenarios/test_module_runner_overview.adoc[test runner] `unit_test_main` manually with the default
xref:adv_scenarios/test_module_init_overview.adoc[initialization function] `init_unit_test` as argument.
You need to define {boost_test_no_main} (its value is irrelevant) in the main file:

[%header%autowidth,cols="2*"]
|===
|In *exactly one* file
|In all other files

a|
[source,cpp]
----
#define BOOST_TEST_MODULE test module name
#define BOOST_TEST_DYN_LINK
#define BOOST_TEST_NO_MAIN
#include <boost/test/unit_test.hpp>

// entry point:
int main(int argc, char* argv[], char* envp[])
{
  return boost::unit_test::unit_test_main( &init_unit_test, argc, argv );
}
----
a|
[source,cpp]
----
#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>

//
// test cases
//

//
// test cases
//
----

|===

[#init_func]
== Customizing the module's initialization function

In the shared-library variant, it is impossible to customize the initialization function without
xref:adv_scenarios/shared_lib_customizations.adoc#entry_point[customizing the entry point]. We have
to customize both. In one of the source files, you now have to define your custom entry point and
xref:adv_scenarios/test_module_init_overview.adoc[initialization function] `init_unit_test`; next invoke
the default xref:adv_scenarios/test_module_runner_overview.adoc[test runner] `unit_test_main` manually
with `init_unit_test` as argument. You _do not_ define {boost_test_module} in the main file:

[%header%autowidth,cols="2*"]
|===
|In *exactly one* file
|In all other files

a|
[source,cpp]
----
#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>

// initialization function:
bool init_unit_test()
{
  return true;
}

// entry point:
int main(int argc, char* argv[])
{
  return boost::unit_test::unit_test_main( &init_unit_test, argc, argv );
}
----
a|
[source,cpp]
----
#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>

//
// test cases
//

//
// test cases
//

//
// test cases
//
----

|===

For reporting errors that may occur during the initialization,

* either you return `false` (valid only for the new API only, see {boost_test_alternative_init_api})
* or you raise an exception such as `std::runtime_error` or cpp:boost::unit_test::framework::setup_error[boost::unit_test::framework::setup_error]

An error reported in this function aborts the execution of the test module.
