= Header-only variant customizations
:page-aliases: boost_test/adv_scenarios/single_header_customizations.adoc

[#multiple_translation_units]
== Header-only with multiple translation units

It is possible to use the header-only variant of the {utf} even if the test module has multiple translation
units:

* one translation unit should define {boost_test_module} and include `<boost/test/included/unit_test.hpp>`
* all the other translation units should include `<boost/test/unit_test.hpp>`

An example might be the following:

* Translation unit 1, defines {boost_test_module}
`+#define BOOST_TEST_MODULE header-only multiunit test
#include <boost/test/included/unit_test.hpp>
+
BOOST_AUTO_TEST_CASE( test1 )
{
int i = 1;
BOOST_CHECK( i*i == 1 );
}+`
* Translation unit 2, includes `<boost/test/unit_test.hpp>` instead of `<boost/test/included/unit_test.hpp>`:
`+#include <boost/test/unit_test.hpp>
+
BOOST_AUTO_TEST_CASE( test2 )
{
int i = 1;
BOOST_CHECK( i*i == 1 );
}+`

[#entry_point]
== Customizing the module's entry point

In this usage variant and in the translation unit containing the definition of {boost_test_module},
you need to define the macros {boost_test_no_main} and
{boost_test_alternative_init_api} (their values are irrelevant) prior to including any of the framework's headers.
Next, you have to define your custom entry point, and invoke the default xref:adv_scenarios/test_module_runner_overview.adoc[test runner] `unit_test_main` manually with the default xref:adv_scenarios/test_module_init_overview.adoc[initialization function] `init_unit_test` as argument.

// tag reference: doc/modules/ROOT/examples/custom_main.run-fail.cpp
:bt-name: custom_main
:bt-rule: run-fail
:bt-descr: using custom entry point
include::partial$bt_example.adoc[]

In the above example, a custom entry point was selected because the test module, in addition to command line arguments,
needs to obtain also the information about environment variables.

[NOTE]
====
The above example also illustrates that it makes sense to define both {boost_test_module} and
{boost_test_no_main}. This way, no `main` is generated by the framework, but the name specified by {boost_test_module}
is assigned to the xref:tests_organization/master_test_suite.adoc[Master test suite].
====

NOTE: The reason for defining {boost_test_alternative_init_api} is described xref:adv_scenarios/obsolete_init_func.adoc[here].

[#init_func]
== Customizing the module's initialization function

In this usage variant, you do not define macro {boost_test_module} and instead provide the definition of function
`init_unit_test`. This is going to be the custom initialization function. The default xref:adv_scenarios/test_module_runner_overview.adoc[test runner] will use it to initialize the test module.

// tag reference: doc/modules/ROOT/examples/custom_init.run-fail.cpp
:bt-name: custom_init
:bt-rule: run-fail
:bt-descr: using custom initialization function
include::partial$bt_example.adoc[]

[NOTE]
====
Because we overwrote the default initialization function, it does no longer assign any name to the xref:tests_organization/master_test_suite.adoc[master test suite]. Therefore the default name ("Master Test
Suite") is used.
====

For reporting errors that may occur during the initialization,

* either you return `false` (valid only for the new API only, see {boost_test_alternative_init_api})
* or you raise an exception such as `std::runtime_error` or cpp:boost::unit_test::framework::setup_error[boost::unit_test::framework::setup_error]

An error reported in this function aborts the execution of the test module.

NOTE: The reason for defining {boost_test_alternative_init_api} is described xref:adv_scenarios/obsolete_init_func.adoc[here].
