= Static-library variant customizations
:page-aliases: boost_test/adv_scenarios/static_lib_customizations.adoc, boost_test/adv_scenarios/static_lib_customizations/entry_point.adoc, boost_test/adv_scenarios/static_lib_customizations/init_func.adoc

[#entry_point]
== Customizing the module's entry point

In the static library variant, customizing the main entry point is quite troublesome, because the definition
of function `main` is already compiled into the static library. This requires you to rebuild the _Unit Test Framework_
static library with the defined symbol xref:{boost_test_no_main}[`BOOST_TEST_NO_MAIN`]. In the Boost root directory you need to
invoke command

[source,cpp]
----
> b2 --with-test link=static define=BOOST_TEST_NO_MAIN define=BOOST_TEST_ALTERNATIVE_INIT_API install
----

[WARNING]
====
This removal of entry point definition from the static library will affect everybody else who is
linking against the library. It may be less intrusive to switch to the
xref:adv_scenarios/shared_lib_customizations.adoc[shared library usage variant] instead.
====

In one of the source files, you now have to define your custom entry point, and invoke the default
xref:adv_scenarios/test_module_runner_overview.adoc[test runner] `unit_test_main` manually with
the default xref:adv_scenarios/test_module_init_overview.adoc[initialization function] `init_unit_test`
as the first argument. There is no need to define xref:{boost_test_no_main}[`BOOST_TEST_NO_MAIN`] in your source code, but you need
to define xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`] in the main file:

[%header%autowidth,cols="2*"]
|===
|In *exactly one* file
|In all other files

a|
[source,cpp]
----
#define BOOST_TEST_MODULE test module name
#define BOOST_TEST_ALTERNATIVE_INIT_API
#include <boost/test/unit_test.hpp>

// entry point:
int main(int argc, char* argv[], char* envp[])
{
  return utf::unit_test_main(init_unit_test, argc, argv);
}
----
a|
[source,cpp]
----
#include <boost/test/unit_test.hpp>

//
// test cases
//

//
// test cases
//
----

|===

[NOTE]
====
The reason for defining xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`] is described
 xref:adv_scenarios/obsolete_init_func.adoc[here].
====

[#init_func]
== Customizing the module's initialization function

In the static library variant, customizing the main entry point is quite troublesome, because the default test
runner compiled into the static library uses the obsolete initialization function signature. This requires you
to rebuild the _Unit Test Framework_ static library with the defined symbol xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`]. In the Boost
root directory you need to invoke command

[source,cpp]
----
> b2 --with-test link=static define=BOOST_TEST_ALTERNATIVE_INIT_API install
----

[WARNING]
====
This alteration of the static library will affect everybody else who is linking against the
library. Consider using the xref:adv_scenarios/obsolete_init_func.adoc[obsolete test initialization function],
which requires no rebuilding. Alternatively, it may be less intrusive to switch to the
xref:adv_scenarios/shared_lib_customizations.adoc[shared library usage variant] instead.
====

In one of the source files, you now have to define your custom initialization function with signature:

[source,cpp]
----
bool init_unit_test();
----

The default xref:adv_scenarios/test_module_runner_overview.adoc[test runner] will use it to initialize
the test module. In your source code, you no longer define macro xref:{boost_test_module}[`BOOST_TEST_MODULE`]; instead, you need to
define xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`] in the main file:

[%header%autowidth,cols="2*"]
|===
|In *exactly one* file
|In all other files

a|
[source,cpp]
----
#define BOOST_TEST_ALTERNATIVE_INIT_API
#include <boost/test/unit_test.hpp>

// init func:
bool init_unit_test()
{
  return true;
}
----
a|
[source,cpp]
----
#include <boost/test/unit_test.hpp>

//
// test cases
//

// test cases
//
----

|===

For reporting errors that may occur during the initialization,

* either you return `false` (valid only for the new API only, see xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`])
* or you raise an exception such as `std::runtime_error` or cpp:boost::unit_test::framework::setup_error[boost::unit_test::framework::setup_error]

An error reported in this function aborts the execution of the test module.

[NOTE]
====
The reason for defining xref:{boost_test_alternative_init_api}[`BOOST_TEST_ALTERNATIVE_INIT_API`] is described
 xref:adv_scenarios/obsolete_init_func.adoc[here].
====
