= Test module runner
:page-aliases: boost_test/adv_scenarios/test_module_runner_overview.adoc

A _test module runner_ is an _orchestrator_ or a _driver_ that, given the test tree, ensures the test tree is initialized,
tests are executed and necessary reports generated. It performs the following operations:

* initialize the test module using the supplied xref:adv_scenarios/test_module_init_overview.adoc[_initialization function_];
* select output media for the test log and the test results report;
* execute test cases as specified by run-time parameters;
* produce the test results report;
* generate the appropriate return code.

The _Unit Test Framework_ comes with the default test runner. There is no need to call it explicitly. The default generated test module's
xref:adv_scenarios/entry_point_overview.adoc[entry point] invokes the default test runner. The default test runner is
declared with the following signature:

[source,cpp]
----
namespace boost { namespace unit_test {

  typedef bool (*init_unit_test_func)();

  int unit_test_main( init_unit_test_func init_func, int argc, char* argv[] );

} }
----

The test runner may return one of the following values:

[%header%autowidth,cols="2*"]
|===
|Value
|Meaning

|`boost::exit_success`
a|
* No errors occurred during testing, or
* the success result was forced with command-line argument `--[link boost_test.utf_reference.rt_param_reference.result_code`result_code`]=no`.

|`boost::exit_test_failure`
a|
* Non-fatal errors detected and no uncaught exceptions were thrown during testing, or
* the initialization of the _Unit Test Framework_ failed.

|`boost::exit_exception_failure`
a|
* Fatal errors were detected, or
* uncaught exceptions thrown during testing.

|===

An advanced test runner may provide additional features, including interactive GUI interfaces, test coverage and profiling support.
