#
# Copyright 2020-2021 Peter Dimov
# Copyright 2021 Andrey Semashev
# Copyright 2021-2026 Alexander Grund
# Copyright 2022-2025 James E. King III
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
# This workflow uses the Boost.CI reusable workflow which builds a variety of
# configurations of your project, runs tests, and generates code coverage reports.
#
# To use it, copy this file into your repository as `.github/workflows/ci.yml` and
# customize it appropriately.
#
---
name: Boost.CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - bugfix/**
      - feature/**
      - fix/**
      - github/**
      - pr/**
    paths-ignore:
      - LICENSE
      - meta/**
      - README.md

jobs:
  call-boost-ci:
    name: Run Boost.CI
    uses: boostorg/boost-ci/.github/workflows/reusable.yml@master
    # Customization:
    with:
       enable_pr_coverage: false  # Disabled: Too many issues with lcov
       enable_cygwin: false
       depinst_args: --include doc/examples
       enable_mingw: false
       enable_multiarch: false
       timeout: 360
       max_cxx_stds_per_job: 2  # Too many configurations per job(?)
       exclude_jobs: |
          compiler: 'gcc-4.8,gcc-4.9'                     # Not C++11 compliant enough for Boost.Test
          compiler: 'clang-11,clang-12', cxxstd: '17,20'  # github_issue_475
          compiler: clang-8, cxxstd: 11                   # Subset of C++ stds as GHA fails w/o showing output
          os: macos-26                                    # basic_cstring-test: Missing 'std::char_traits<unsigned char>' on ARM
          os: ubuntu-24.04-arm                            # system-exception-test fails
          os: macos, sanitize: yes, cxxstd: '11,14,17,20' # Reduce number of configurations
          os: windows, cxxstd: '11,14'                    # Reduce number of configurations
          os: windows, address-model: 32                  # Reduce number of configurations, test only 64bit
          os: ubuntu, sanitize: yes                       # Memory leaks in test-macro-global-fixture, not on macos
    secrets:
      # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  Disabled: Too many issues with lcov
      COVERITY_SCAN_NOTIFICATION_EMAIL: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
      COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
